// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.20.1
// 	protoc        v3.6.1
// source: protocol/collections.proto

package protocol

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CollectionOp int32

const (
	CollectionOp_COLLECTION_OP_UNSPECIFIED CollectionOp = 0
	CollectionOp_COLLECTION_OP_REPLACE     CollectionOp = 1
	CollectionOp_COLLECTION_OP_ADD         CollectionOp = 2
	CollectionOp_COLLECTION_OP_UPDATE      CollectionOp = 3
	CollectionOp_COLLECTION_OP_REMOVE      CollectionOp = 4
)

// Enum value maps for CollectionOp.
var (
	CollectionOp_name = map[int32]string{
		0: "COLLECTION_OP_UNSPECIFIED",
		1: "COLLECTION_OP_REPLACE",
		2: "COLLECTION_OP_ADD",
		3: "COLLECTION_OP_UPDATE",
		4: "COLLECTION_OP_REMOVE",
	}
	CollectionOp_value = map[string]int32{
		"COLLECTION_OP_UNSPECIFIED": 0,
		"COLLECTION_OP_REPLACE":     1,
		"COLLECTION_OP_ADD":         2,
		"COLLECTION_OP_UPDATE":      3,
		"COLLECTION_OP_REMOVE":      4,
	}
)

func (x CollectionOp) Enum() *CollectionOp {
	p := new(CollectionOp)
	*p = x
	return p
}

func (x CollectionOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CollectionOp) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_collections_proto_enumTypes[0].Descriptor()
}

func (CollectionOp) Type() protoreflect.EnumType {
	return &file_protocol_collections_proto_enumTypes[0]
}

func (x CollectionOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CollectionOp.Descriptor instead.
func (CollectionOp) EnumDescriptor() ([]byte, []int) {
	return file_protocol_collections_proto_rawDescGZIP(), []int{0}
}

var File_protocol_collections_proto protoreflect.FileDescriptor

var file_protocol_collections_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x63, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6e, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2a, 0x93, 0x01, 0x0a, 0x0c, 0x43, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x12, 0x1d, 0x0a, 0x19, 0x43, 0x4f,
	0x4c, 0x4c, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4f, 0x50, 0x5f, 0x55, 0x4e, 0x53, 0x50,
	0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x43, 0x4f, 0x4c,
	0x4c, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4f, 0x50, 0x5f, 0x52, 0x45, 0x50, 0x4c, 0x41,
	0x43, 0x45, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x43, 0x4f, 0x4c, 0x4c, 0x45, 0x43, 0x54, 0x49,
	0x4f, 0x4e, 0x5f, 0x4f, 0x50, 0x5f, 0x41, 0x44, 0x44, 0x10, 0x02, 0x12, 0x18, 0x0a, 0x14, 0x43,
	0x4f, 0x4c, 0x4c, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4f, 0x50, 0x5f, 0x55, 0x50, 0x44,
	0x41, 0x54, 0x45, 0x10, 0x03, 0x12, 0x18, 0x0a, 0x14, 0x43, 0x4f, 0x4c, 0x4c, 0x45, 0x43, 0x54,
	0x49, 0x4f, 0x4e, 0x5f, 0x4f, 0x50, 0x5f, 0x52, 0x45, 0x4d, 0x4f, 0x56, 0x45, 0x10, 0x04, 0x42,
	0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x31, 0x33,
	0x6b, 0x2f, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x2d, 0x73, 0x74, 0x61, 0x6c, 0x6b, 0x65, 0x72, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_protocol_collections_proto_rawDescOnce sync.Once
	file_protocol_collections_proto_rawDescData = file_protocol_collections_proto_rawDesc
)

func file_protocol_collections_proto_rawDescGZIP() []byte {
	file_protocol_collections_proto_rawDescOnce.Do(func() {
		file_protocol_collections_proto_rawDescData = protoimpl.X.CompressGZIP(file_protocol_collections_proto_rawDescData)
	})
	return file_protocol_collections_proto_rawDescData
}

var file_protocol_collections_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protocol_collections_proto_goTypes = []interface{}{
	(CollectionOp)(0), // 0: ns.protocol.CollectionOp
}
var file_protocol_collections_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocol_collections_proto_init() }
func file_protocol_collections_proto_init() {
	if File_protocol_collections_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protocol_collections_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_collections_proto_goTypes,
		DependencyIndexes: file_protocol_collections_proto_depIdxs,
		EnumInfos:         file_protocol_collections_proto_enumTypes,
	}.Build()
	File_protocol_collections_proto = out.File
	file_protocol_collections_proto_rawDesc = nil
	file_protocol_collections_proto_goTypes = nil
	file_protocol_collections_proto_depIdxs = nil
}
