// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol/match.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Match struct {
	MatchId              uint64               `protobuf:"varint,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	LobbyId              uint64               `protobuf:"varint,2,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	LobbyType            LobbyType            `protobuf:"varint,3,opt,name=lobby_type,json=lobbyType,proto3,enum=protocol.LobbyType" json:"lobby_type,omitempty"`
	LeagueId             uint64               `protobuf:"varint,4,opt,name=league_id,json=leagueId,proto3" json:"league_id,omitempty"`
	SeriesId             uint64               `protobuf:"varint,5,opt,name=series_id,json=seriesId,proto3" json:"series_id,omitempty"`
	GameMode             GameMode             `protobuf:"varint,6,opt,name=game_mode,json=gameMode,proto3,enum=protocol.GameMode" json:"game_mode,omitempty"`
	AverageMmr           uint32               `protobuf:"varint,7,opt,name=average_mmr,json=averageMmr,proto3" json:"average_mmr,omitempty"`
	RadiantTeamId        uint64               `protobuf:"varint,8,opt,name=radiant_team_id,json=radiantTeamId,proto3" json:"radiant_team_id,omitempty"`
	RadiantTeamName      string               `protobuf:"bytes,9,opt,name=radiant_team_name,json=radiantTeamName,proto3" json:"radiant_team_name,omitempty"`
	RadiantTeamTag       string               `protobuf:"bytes,10,opt,name=radiant_team_tag,json=radiantTeamTag,proto3" json:"radiant_team_tag,omitempty"`
	RadiantTeamLogo      uint64               `protobuf:"varint,11,opt,name=radiant_team_logo,json=radiantTeamLogo,proto3" json:"radiant_team_logo,omitempty"`
	RadiantTeamLogoUrl   string               `protobuf:"bytes,12,opt,name=radiant_team_logo_url,json=radiantTeamLogoUrl,proto3" json:"radiant_team_logo_url,omitempty"`
	DireTeamId           uint64               `protobuf:"varint,13,opt,name=dire_team_id,json=direTeamId,proto3" json:"dire_team_id,omitempty"`
	DireTeamName         string               `protobuf:"bytes,14,opt,name=dire_team_name,json=direTeamName,proto3" json:"dire_team_name,omitempty"`
	DireTeamTag          string               `protobuf:"bytes,15,opt,name=dire_team_tag,json=direTeamTag,proto3" json:"dire_team_tag,omitempty"`
	DireTeamLogo         uint64               `protobuf:"varint,16,opt,name=dire_team_logo,json=direTeamLogo,proto3" json:"dire_team_logo,omitempty"`
	DireTeamLogoUrl      string               `protobuf:"bytes,17,opt,name=dire_team_logo_url,json=direTeamLogoUrl,proto3" json:"dire_team_logo_url,omitempty"`
	ActivateTime         *timestamp.Timestamp `protobuf:"bytes,18,opt,name=activate_time,json=activateTime,proto3" json:"activate_time,omitempty"`
	DeactivateTime       *timestamp.Timestamp `protobuf:"bytes,19,opt,name=deactivate_time,json=deactivateTime,proto3" json:"deactivate_time,omitempty"`
	LastUpdateTime       *timestamp.Timestamp `protobuf:"bytes,20,opt,name=last_update_time,json=lastUpdateTime,proto3" json:"last_update_time,omitempty"`
	StartTime            *timestamp.Timestamp `protobuf:"bytes,21,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	SeriesType           uint32               `protobuf:"varint,22,opt,name=series_type,json=seriesType,proto3" json:"series_type,omitempty"`
	SeriesGame           uint32               `protobuf:"varint,23,opt,name=series_game,json=seriesGame,proto3" json:"series_game,omitempty"`
	Duration             uint32               `protobuf:"varint,24,opt,name=duration,proto3" json:"duration,omitempty"`
	RadiantScore         uint32               `protobuf:"varint,25,opt,name=radiant_score,json=radiantScore,proto3" json:"radiant_score,omitempty"`
	DireScore            uint32               `protobuf:"varint,26,opt,name=dire_score,json=direScore,proto3" json:"dire_score,omitempty"`
	Outcome              MatchOutcome         `protobuf:"varint,27,opt,name=outcome,proto3,enum=protocol.MatchOutcome" json:"outcome,omitempty"`
	Players              []*Match_Player      `protobuf:"bytes,100,rep,name=players,proto3" json:"players,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Match) Reset()         { *m = Match{} }
func (m *Match) String() string { return proto.CompactTextString(m) }
func (*Match) ProtoMessage()    {}
func (*Match) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1a7279fe70790cb, []int{0}
}

func (m *Match) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Match.Unmarshal(m, b)
}
func (m *Match) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Match.Marshal(b, m, deterministic)
}
func (m *Match) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Match.Merge(m, src)
}
func (m *Match) XXX_Size() int {
	return xxx_messageInfo_Match.Size(m)
}
func (m *Match) XXX_DiscardUnknown() {
	xxx_messageInfo_Match.DiscardUnknown(m)
}

var xxx_messageInfo_Match proto.InternalMessageInfo

func (m *Match) GetMatchId() uint64 {
	if m != nil {
		return m.MatchId
	}
	return 0
}

func (m *Match) GetLobbyId() uint64 {
	if m != nil {
		return m.LobbyId
	}
	return 0
}

func (m *Match) GetLobbyType() LobbyType {
	if m != nil {
		return m.LobbyType
	}
	return LobbyType_LOBBY_TYPE_CASUAL_MATCH
}

func (m *Match) GetLeagueId() uint64 {
	if m != nil {
		return m.LeagueId
	}
	return 0
}

func (m *Match) GetSeriesId() uint64 {
	if m != nil {
		return m.SeriesId
	}
	return 0
}

func (m *Match) GetGameMode() GameMode {
	if m != nil {
		return m.GameMode
	}
	return GameMode_GAME_MODE_NONE
}

func (m *Match) GetAverageMmr() uint32 {
	if m != nil {
		return m.AverageMmr
	}
	return 0
}

func (m *Match) GetRadiantTeamId() uint64 {
	if m != nil {
		return m.RadiantTeamId
	}
	return 0
}

func (m *Match) GetRadiantTeamName() string {
	if m != nil {
		return m.RadiantTeamName
	}
	return ""
}

func (m *Match) GetRadiantTeamTag() string {
	if m != nil {
		return m.RadiantTeamTag
	}
	return ""
}

func (m *Match) GetRadiantTeamLogo() uint64 {
	if m != nil {
		return m.RadiantTeamLogo
	}
	return 0
}

func (m *Match) GetRadiantTeamLogoUrl() string {
	if m != nil {
		return m.RadiantTeamLogoUrl
	}
	return ""
}

func (m *Match) GetDireTeamId() uint64 {
	if m != nil {
		return m.DireTeamId
	}
	return 0
}

func (m *Match) GetDireTeamName() string {
	if m != nil {
		return m.DireTeamName
	}
	return ""
}

func (m *Match) GetDireTeamTag() string {
	if m != nil {
		return m.DireTeamTag
	}
	return ""
}

func (m *Match) GetDireTeamLogo() uint64 {
	if m != nil {
		return m.DireTeamLogo
	}
	return 0
}

func (m *Match) GetDireTeamLogoUrl() string {
	if m != nil {
		return m.DireTeamLogoUrl
	}
	return ""
}

func (m *Match) GetActivateTime() *timestamp.Timestamp {
	if m != nil {
		return m.ActivateTime
	}
	return nil
}

func (m *Match) GetDeactivateTime() *timestamp.Timestamp {
	if m != nil {
		return m.DeactivateTime
	}
	return nil
}

func (m *Match) GetLastUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdateTime
	}
	return nil
}

func (m *Match) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *Match) GetSeriesType() uint32 {
	if m != nil {
		return m.SeriesType
	}
	return 0
}

func (m *Match) GetSeriesGame() uint32 {
	if m != nil {
		return m.SeriesGame
	}
	return 0
}

func (m *Match) GetDuration() uint32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Match) GetRadiantScore() uint32 {
	if m != nil {
		return m.RadiantScore
	}
	return 0
}

func (m *Match) GetDireScore() uint32 {
	if m != nil {
		return m.DireScore
	}
	return 0
}

func (m *Match) GetOutcome() MatchOutcome {
	if m != nil {
		return m.Outcome
	}
	return MatchOutcome_MATCH_OUTCOME_UNKNOWN
}

func (m *Match) GetPlayers() []*Match_Player {
	if m != nil {
		return m.Players
	}
	return nil
}

type Match_Player struct {
	AccountId            uint32   `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	HeroId               uint64   `protobuf:"varint,2,opt,name=hero_id,json=heroId,proto3" json:"hero_id,omitempty"`
	PlayerSlot           uint32   `protobuf:"varint,3,opt,name=player_slot,json=playerSlot,proto3" json:"player_slot,omitempty"`
	ProName              string   `protobuf:"bytes,4,opt,name=pro_name,json=proName,proto3" json:"pro_name,omitempty"`
	Kills                uint32   `protobuf:"varint,5,opt,name=kills,proto3" json:"kills,omitempty"`
	Deaths               uint32   `protobuf:"varint,6,opt,name=deaths,proto3" json:"deaths,omitempty"`
	Assists              uint32   `protobuf:"varint,7,opt,name=assists,proto3" json:"assists,omitempty"`
	Items                []int64  `protobuf:"varint,8,rep,packed,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Match_Player) Reset()         { *m = Match_Player{} }
func (m *Match_Player) String() string { return proto.CompactTextString(m) }
func (*Match_Player) ProtoMessage()    {}
func (*Match_Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1a7279fe70790cb, []int{0, 0}
}

func (m *Match_Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Match_Player.Unmarshal(m, b)
}
func (m *Match_Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Match_Player.Marshal(b, m, deterministic)
}
func (m *Match_Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Match_Player.Merge(m, src)
}
func (m *Match_Player) XXX_Size() int {
	return xxx_messageInfo_Match_Player.Size(m)
}
func (m *Match_Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Match_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Match_Player proto.InternalMessageInfo

func (m *Match_Player) GetAccountId() uint32 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *Match_Player) GetHeroId() uint64 {
	if m != nil {
		return m.HeroId
	}
	return 0
}

func (m *Match_Player) GetPlayerSlot() uint32 {
	if m != nil {
		return m.PlayerSlot
	}
	return 0
}

func (m *Match_Player) GetProName() string {
	if m != nil {
		return m.ProName
	}
	return ""
}

func (m *Match_Player) GetKills() uint32 {
	if m != nil {
		return m.Kills
	}
	return 0
}

func (m *Match_Player) GetDeaths() uint32 {
	if m != nil {
		return m.Deaths
	}
	return 0
}

func (m *Match_Player) GetAssists() uint32 {
	if m != nil {
		return m.Assists
	}
	return 0
}

func (m *Match_Player) GetItems() []int64 {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*Match)(nil), "protocol.Match")
	proto.RegisterType((*Match_Player)(nil), "protocol.Match.Player")
}

func init() { proto.RegisterFile("protocol/match.proto", fileDescriptor_d1a7279fe70790cb) }

var fileDescriptor_d1a7279fe70790cb = []byte{
	// 754 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x4d, 0x6f, 0xdc, 0x36,
	0x10, 0xc5, 0xd6, 0xf6, 0x7e, 0xcc, 0xae, 0xd6, 0x0e, 0xe3, 0x38, 0xcc, 0x06, 0x85, 0x85, 0xb4,
	0x28, 0x84, 0x16, 0xd5, 0x36, 0xce, 0xa1, 0xc8, 0xa9, 0x40, 0x5b, 0xa0, 0x58, 0x20, 0x6e, 0x0b,
	0xc5, 0xb9, 0xf4, 0x22, 0x70, 0x45, 0x56, 0x2b, 0x98, 0x14, 0x05, 0x92, 0x0a, 0xe0, 0x73, 0xff,
	0x65, 0x7f, 0x4d, 0xc1, 0xa1, 0xb4, 0xda, 0xad, 0x0f, 0xbe, 0x69, 0xde, 0x7b, 0xf3, 0x46, 0x43,
	0xcc, 0x0c, 0x5c, 0x36, 0x46, 0x3b, 0x5d, 0x68, 0xb9, 0x56, 0xcc, 0x15, 0xbb, 0x14, 0x43, 0x32,
	0xed, 0xd1, 0xd5, 0x75, 0xa9, 0x75, 0x29, 0xc5, 0x1a, 0x81, 0x6d, 0xfb, 0xf7, 0xda, 0x55, 0x4a,
	0x58, 0xc7, 0x54, 0x13, 0xa4, 0xab, 0xc1, 0x40, 0xd4, 0xad, 0xb2, 0x01, 0x7d, 0xf3, 0xcf, 0x1c,
	0xce, 0x6e, 0xbd, 0x21, 0x79, 0x05, 0x53, 0x74, 0xce, 0x2b, 0x4e, 0x47, 0xf1, 0x28, 0x39, 0xcd,
	0x26, 0x18, 0x6f, 0xb8, 0xa7, 0xa4, 0xde, 0x6e, 0x1f, 0x3c, 0xf5, 0x45, 0xa0, 0x30, 0xde, 0x70,
	0x72, 0x03, 0x10, 0x28, 0xf7, 0xd0, 0x08, 0x7a, 0x12, 0x8f, 0x92, 0xe5, 0xcd, 0xf3, 0xb4, 0x2f,
	0x95, 0x7e, 0xf0, 0xdc, 0xdd, 0x43, 0x23, 0xb2, 0x99, 0xec, 0x3f, 0xc9, 0x6b, 0x98, 0x49, 0xc1,
	0xca, 0x56, 0x78, 0xbf, 0x53, 0xf4, 0x9b, 0x06, 0x60, 0xc3, 0x3d, 0x69, 0x85, 0xa9, 0x84, 0xf5,
	0xe4, 0x59, 0x20, 0x03, 0xb0, 0xe1, 0x64, 0x0d, 0xb3, 0x92, 0x29, 0x91, 0x2b, 0xcd, 0x05, 0x1d,
	0x63, 0x31, 0x32, 0x14, 0xfb, 0x8d, 0x29, 0x71, 0xab, 0xb9, 0xc8, 0xa6, 0x65, 0xf7, 0x45, 0xae,
	0x61, 0xce, 0x3e, 0x0b, 0xc3, 0x4a, 0x91, 0x2b, 0x65, 0xe8, 0x24, 0x1e, 0x25, 0x51, 0x06, 0x1d,
	0x74, 0xab, 0x0c, 0xf9, 0x06, 0xce, 0x0d, 0xe3, 0x15, 0xab, 0x5d, 0xee, 0x04, 0x53, 0xbe, 0xe8,
	0x14, 0x8b, 0x46, 0x1d, 0x7c, 0x27, 0x98, 0xda, 0x70, 0xf2, 0x2d, 0x3c, 0x3b, 0xd2, 0xd5, 0x4c,
	0x09, 0x3a, 0x8b, 0x47, 0xc9, 0x2c, 0x3b, 0x3f, 0x50, 0xfe, 0xce, 0x94, 0x20, 0x09, 0x5c, 0x1c,
	0x69, 0x1d, 0x2b, 0x29, 0xa0, 0x74, 0x79, 0x20, 0xbd, 0x63, 0xe5, 0x23, 0x57, 0xa9, 0x4b, 0x4d,
	0xe7, 0x58, 0xff, 0xd0, 0xf5, 0x83, 0x2e, 0x35, 0x79, 0x0b, 0x2f, 0x1e, 0x69, 0xf3, 0xd6, 0x48,
	0xba, 0x40, 0x6b, 0xf2, 0x3f, 0xfd, 0x27, 0x23, 0x49, 0x0c, 0x0b, 0x5e, 0x19, 0xb1, 0xef, 0x2c,
	0x42, 0x67, 0xf0, 0x58, 0xd7, 0xd6, 0xd7, 0xb0, 0x1c, 0x14, 0xd8, 0xd3, 0x12, 0xdd, 0x16, 0xbd,
	0x06, 0x1b, 0x7a, 0x03, 0xd1, 0xa0, 0xf2, 0xdd, 0x9c, 0xa3, 0x68, 0xde, 0x8b, 0x7c, 0x2b, 0x47,
	0x4e, 0xd8, 0xc7, 0x05, 0x56, 0xdb, 0x3b, 0x61, 0x13, 0xdf, 0x01, 0x39, 0x56, 0x61, 0x07, 0xcf,
	0xc2, 0x3b, 0x1e, 0x2a, 0xfd, 0xef, 0xff, 0x04, 0x11, 0x2b, 0x5c, 0xf5, 0x99, 0x39, 0x91, 0xfb,
	0x69, 0xa6, 0x24, 0x1e, 0x25, 0xf3, 0x9b, 0x55, 0x1a, 0x46, 0x3d, 0xed, 0x47, 0x3d, 0xbd, 0xeb,
	0x47, 0x3d, 0x5b, 0xf4, 0x09, 0x1e, 0x22, 0xbf, 0xc0, 0x39, 0x17, 0xc7, 0x16, 0xcf, 0x9f, 0xb4,
	0x58, 0x0e, 0x29, 0x68, 0xf2, 0x2b, 0x5c, 0x48, 0x66, 0x5d, 0xde, 0x36, 0x7c, 0xef, 0x72, 0xf9,
	0xb4, 0x8b, 0xcf, 0xf9, 0x84, 0x29, 0xe8, 0xf2, 0x1e, 0xc0, 0x3a, 0x66, 0x5c, 0xc8, 0x7f, 0xf1,
	0x64, 0xfe, 0x0c, 0xd5, 0x98, 0x7a, 0x0d, 0xf3, 0x6e, 0x23, 0x70, 0xc7, 0xae, 0xc2, 0x0c, 0x07,
	0x08, 0xf7, 0x69, 0x10, 0xf8, 0xb9, 0xa7, 0x2f, 0x0f, 0x05, 0x7e, 0x27, 0xc8, 0x0a, 0xa6, 0xbc,
	0x35, 0xcc, 0x55, 0xba, 0xa6, 0x14, 0xd9, 0x7d, 0x4c, 0xbe, 0x82, 0x7e, 0xd2, 0x73, 0x5b, 0x68,
	0x23, 0xe8, 0x2b, 0x14, 0x2c, 0x3a, 0xf0, 0xa3, 0xc7, 0xc8, 0x97, 0x80, 0x43, 0xd3, 0x29, 0x56,
	0xa8, 0x98, 0x79, 0x24, 0xd0, 0x3f, 0xc0, 0x44, 0xb7, 0xae, 0xd0, 0x4a, 0xd0, 0xd7, 0xb8, 0x94,
	0x57, 0xc3, 0x52, 0xe2, 0x71, 0xf9, 0x23, 0xb0, 0x59, 0x2f, 0xf3, 0x19, 0x8d, 0x64, 0x0f, 0xc2,
	0x58, 0xca, 0xe3, 0x93, 0x64, 0xfe, 0x28, 0x23, 0xfd, 0x13, 0xe9, 0xac, 0x97, 0xad, 0xfe, 0x1d,
	0xc1, 0x38, 0x60, 0xfe, 0x6f, 0x58, 0x51, 0xe8, 0xb6, 0x76, 0xfd, 0xad, 0x8a, 0xb2, 0x59, 0x87,
	0x6c, 0x38, 0x79, 0x09, 0x93, 0x9d, 0x30, 0x7a, 0x38, 0x56, 0x63, 0x1f, 0x6e, 0xb8, 0x7f, 0xa7,
	0xe0, 0x96, 0x5b, 0xa9, 0x1d, 0x1e, 0xab, 0x28, 0x83, 0x00, 0x7d, 0x94, 0xda, 0xf9, 0x3b, 0xd7,
	0x18, 0x1d, 0xf6, 0xe0, 0x14, 0x67, 0x72, 0xd2, 0x18, 0x8d, 0x2b, 0x70, 0x09, 0x67, 0xf7, 0x95,
	0x94, 0x16, 0x4f, 0x52, 0x94, 0x85, 0x80, 0x5c, 0xc1, 0x98, 0x0b, 0xe6, 0x76, 0x16, 0x8f, 0x51,
	0x94, 0x75, 0x11, 0xa1, 0x30, 0x61, 0xd6, 0x56, 0xd6, 0xd9, 0xee, 0xe4, 0xf4, 0xa1, 0xf7, 0xa9,
	0x9c, 0x50, 0x96, 0x4e, 0xe3, 0x93, 0xe4, 0x24, 0x0b, 0xc1, 0xcf, 0xef, 0xff, 0xfa, 0xb1, 0xac,
	0xdc, 0xae, 0xdd, 0xa6, 0x85, 0x56, 0xeb, 0xb7, 0xef, 0xee, 0xd7, 0x75, 0x55, 0xee, 0xdc, 0xf7,
	0xd6, 0x31, 0x79, 0x2f, 0xcc, 0xba, 0xaa, 0x9d, 0x30, 0x35, 0x93, 0xc3, 0x75, 0xef, 0x5f, 0x6b,
	0x3b, 0xc6, 0xaf, 0x77, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x3b, 0x51, 0x2b, 0xe5, 0x20, 0x06,
	0x00, 0x00,
}
