// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol/player.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Player struct {
	AccountId            uint32   `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PersonaName          string   `protobuf:"bytes,3,opt,name=persona_name,json=personaName,proto3" json:"persona_name,omitempty"`
	AvatarUrl            string   `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	AvatarMediumUrl      string   `protobuf:"bytes,5,opt,name=avatar_medium_url,json=avatarMediumUrl,proto3" json:"avatar_medium_url,omitempty"`
	AvatarFullUrl        string   `protobuf:"bytes,6,opt,name=avatar_full_url,json=avatarFullUrl,proto3" json:"avatar_full_url,omitempty"`
	IsPro                bool     `protobuf:"varint,7,opt,name=is_pro,json=isPro,proto3" json:"is_pro,omitempty"`
	Slug                 string   `protobuf:"bytes,8,opt,name=slug,proto3" json:"slug,omitempty"`
	Team                 *Team    `protobuf:"bytes,100,opt,name=team,proto3" json:"team,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_45d8949b85fa93d9, []int{0}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetAccountId() uint32 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *Player) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Player) GetPersonaName() string {
	if m != nil {
		return m.PersonaName
	}
	return ""
}

func (m *Player) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *Player) GetAvatarMediumUrl() string {
	if m != nil {
		return m.AvatarMediumUrl
	}
	return ""
}

func (m *Player) GetAvatarFullUrl() string {
	if m != nil {
		return m.AvatarFullUrl
	}
	return ""
}

func (m *Player) GetIsPro() bool {
	if m != nil {
		return m.IsPro
	}
	return false
}

func (m *Player) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Player) GetTeam() *Team {
	if m != nil {
		return m.Team
	}
	return nil
}

type PlayerMatches struct {
	Player               *Player   `protobuf:"bytes,100,opt,name=player,proto3" json:"player,omitempty"`
	Matches              []*Match  `protobuf:"bytes,101,rep,name=matches,proto3" json:"matches,omitempty"`
	KnownPlayers         []*Player `protobuf:"bytes,102,rep,name=known_players,json=knownPlayers,proto3" json:"known_players,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PlayerMatches) Reset()         { *m = PlayerMatches{} }
func (m *PlayerMatches) String() string { return proto.CompactTextString(m) }
func (*PlayerMatches) ProtoMessage()    {}
func (*PlayerMatches) Descriptor() ([]byte, []int) {
	return fileDescriptor_45d8949b85fa93d9, []int{1}
}

func (m *PlayerMatches) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerMatches.Unmarshal(m, b)
}
func (m *PlayerMatches) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerMatches.Marshal(b, m, deterministic)
}
func (m *PlayerMatches) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerMatches.Merge(m, src)
}
func (m *PlayerMatches) XXX_Size() int {
	return xxx_messageInfo_PlayerMatches.Size(m)
}
func (m *PlayerMatches) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerMatches.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerMatches proto.InternalMessageInfo

func (m *PlayerMatches) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

func (m *PlayerMatches) GetMatches() []*Match {
	if m != nil {
		return m.Matches
	}
	return nil
}

func (m *PlayerMatches) GetKnownPlayers() []*Player {
	if m != nil {
		return m.KnownPlayers
	}
	return nil
}

func init() {
	proto.RegisterType((*Player)(nil), "protocol.Player")
	proto.RegisterType((*PlayerMatches)(nil), "protocol.PlayerMatches")
}

func init() { proto.RegisterFile("protocol/player.proto", fileDescriptor_45d8949b85fa93d9) }

var fileDescriptor_45d8949b85fa93d9 = []byte{
	// 371 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x4d, 0xab, 0xd3, 0x40,
	0x18, 0x85, 0xc9, 0xbd, 0xbd, 0x69, 0x3b, 0x6d, 0xac, 0x8e, 0x16, 0x86, 0x82, 0x10, 0xbb, 0x90,
	0x28, 0x98, 0x60, 0x8b, 0x88, 0x5b, 0x17, 0x82, 0x8b, 0x4a, 0x09, 0xba, 0x71, 0x13, 0xa6, 0xc9,
	0xb4, 0x0d, 0x9d, 0x8f, 0x30, 0x1f, 0x8a, 0xbf, 0xc5, 0x8d, 0x3f, 0x55, 0xe6, 0x9d, 0xa4, 0x5d,
	0xdc, 0xdd, 0x3b, 0xe7, 0x3c, 0xe7, 0xc0, 0x1c, 0xb4, 0xec, 0xb4, 0xb2, 0xaa, 0x56, 0xbc, 0xe8,
	0x38, 0xfd, 0xc3, 0x74, 0x0e, 0x6f, 0x3c, 0x19, 0xe4, 0xd5, 0x8b, 0x2b, 0x20, 0xa8, 0xad, 0xcf,
	0xc1, 0x5f, 0x3d, 0xbf, 0xaa, 0x96, 0x51, 0x11, 0xc4, 0xf5, 0xbf, 0x3b, 0x14, 0xef, 0xa1, 0x05,
	0xbf, 0x44, 0x88, 0xd6, 0xb5, 0x72, 0xd2, 0x56, 0x6d, 0x43, 0xa2, 0x34, 0xca, 0x92, 0x72, 0xda,
	0x2b, 0x5f, 0x1b, 0x8c, 0xd1, 0x48, 0x52, 0xc1, 0xc8, 0x5d, 0x1a, 0x65, 0xd3, 0x12, 0x6e, 0xfc,
	0x0a, 0xcd, 0x3b, 0xa6, 0x8d, 0x92, 0xb4, 0x02, 0xef, 0x1e, 0xbc, 0x59, 0xaf, 0x7d, 0xf3, 0x88,
	0x6f, 0xfd, 0x45, 0x2d, 0xd5, 0x95, 0xd3, 0x9c, 0x8c, 0x00, 0x98, 0x06, 0xe5, 0x87, 0xe6, 0xf8,
	0x2d, 0x7a, 0xd6, 0xdb, 0x82, 0x35, 0xad, 0x13, 0x40, 0x3d, 0x00, 0xb5, 0x08, 0xc6, 0x0e, 0x74,
	0xcf, 0xbe, 0x46, 0xbd, 0x54, 0x1d, 0x1d, 0xe7, 0x40, 0xc6, 0x40, 0x26, 0x41, 0xfe, 0xe2, 0x38,
	0xf7, 0xdc, 0x12, 0xc5, 0xad, 0xa9, 0x3a, 0xad, 0xc8, 0x38, 0x8d, 0xb2, 0x49, 0xf9, 0xd0, 0x9a,
	0xbd, 0x56, 0xfe, 0x03, 0x86, 0xbb, 0x13, 0x99, 0x84, 0x0f, 0xf8, 0x1b, 0xaf, 0xd1, 0xc8, 0x8f,
	0x41, 0x9a, 0x34, 0xca, 0x66, 0x9b, 0x27, 0xf9, 0x30, 0x51, 0xfe, 0x9d, 0x51, 0x51, 0x82, 0xb7,
	0xfe, 0x1b, 0xa1, 0x24, 0x4c, 0xb4, 0xf3, 0x6b, 0x32, 0x83, 0x33, 0x14, 0x87, 0xe5, 0xfb, 0xdc,
	0xd3, 0x5b, 0x2e, 0x80, 0x65, 0xef, 0xe3, 0x37, 0x68, 0x2c, 0x42, 0x88, 0xb0, 0xf4, 0x3e, 0x9b,
	0x6d, 0x16, 0x37, 0x14, 0xda, 0xca, 0xc1, 0xc7, 0x1f, 0x50, 0x72, 0x91, 0xea, 0xb7, 0xac, 0x42,
	0xd4, 0x90, 0x23, 0x04, 0x1e, 0x77, 0xcf, 0x01, 0x0b, 0x0f, 0xf3, 0xf9, 0xd3, 0xcf, 0x8f, 0xa7,
	0xd6, 0x9e, 0xdd, 0x21, 0xaf, 0x95, 0x28, 0xde, 0x6f, 0x2f, 0x85, 0x6c, 0x4f, 0x67, 0xfb, 0xce,
	0x58, 0xca, 0x2f, 0x4c, 0x17, 0xad, 0xb4, 0x4c, 0x4b, 0xca, 0x0b, 0xa8, 0x39, 0xb8, 0x63, 0x31,
	0xf4, 0x1d, 0x62, 0xb8, 0xb6, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x85, 0x03, 0xff, 0x25, 0x50,
	0x02, 0x00, 0x00,
}
