// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol/search.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Search struct {
	Players              []*Search_Player `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	HeroIds              []uint64         `protobuf:"varint,2,rep,packed,name=hero_ids,json=heroIds,proto3" json:"hero_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Search) Reset()         { *m = Search{} }
func (m *Search) String() string { return proto.CompactTextString(m) }
func (*Search) ProtoMessage()    {}
func (*Search) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b8684575ab14afc, []int{0}
}

func (m *Search) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Search.Unmarshal(m, b)
}
func (m *Search) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Search.Marshal(b, m, deterministic)
}
func (m *Search) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Search.Merge(m, src)
}
func (m *Search) XXX_Size() int {
	return xxx_messageInfo_Search.Size(m)
}
func (m *Search) XXX_DiscardUnknown() {
	xxx_messageInfo_Search.DiscardUnknown(m)
}

var xxx_messageInfo_Search proto.InternalMessageInfo

func (m *Search) GetPlayers() []*Search_Player {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *Search) GetHeroIds() []uint64 {
	if m != nil {
		return m.HeroIds
	}
	return nil
}

type Search_Player struct {
	AccountId            uint32   `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PersonaName          string   `protobuf:"bytes,3,opt,name=persona_name,json=personaName,proto3" json:"persona_name,omitempty"`
	AvatarUrl            string   `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	AvatarMediumUrl      string   `protobuf:"bytes,5,opt,name=avatar_medium_url,json=avatarMediumUrl,proto3" json:"avatar_medium_url,omitempty"`
	AvatarFullUrl        string   `protobuf:"bytes,6,opt,name=avatar_full_url,json=avatarFullUrl,proto3" json:"avatar_full_url,omitempty"`
	IsPro                bool     `protobuf:"varint,7,opt,name=is_pro,json=isPro,proto3" json:"is_pro,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Search_Player) Reset()         { *m = Search_Player{} }
func (m *Search_Player) String() string { return proto.CompactTextString(m) }
func (*Search_Player) ProtoMessage()    {}
func (*Search_Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_4b8684575ab14afc, []int{0, 0}
}

func (m *Search_Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Search_Player.Unmarshal(m, b)
}
func (m *Search_Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Search_Player.Marshal(b, m, deterministic)
}
func (m *Search_Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Search_Player.Merge(m, src)
}
func (m *Search_Player) XXX_Size() int {
	return xxx_messageInfo_Search_Player.Size(m)
}
func (m *Search_Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Search_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Search_Player proto.InternalMessageInfo

func (m *Search_Player) GetAccountId() uint32 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *Search_Player) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Search_Player) GetPersonaName() string {
	if m != nil {
		return m.PersonaName
	}
	return ""
}

func (m *Search_Player) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *Search_Player) GetAvatarMediumUrl() string {
	if m != nil {
		return m.AvatarMediumUrl
	}
	return ""
}

func (m *Search_Player) GetAvatarFullUrl() string {
	if m != nil {
		return m.AvatarFullUrl
	}
	return ""
}

func (m *Search_Player) GetIsPro() bool {
	if m != nil {
		return m.IsPro
	}
	return false
}

func init() {
	proto.RegisterType((*Search)(nil), "protocol.Search")
	proto.RegisterType((*Search_Player)(nil), "protocol.Search.Player")
}

func init() { proto.RegisterFile("protocol/search.proto", fileDescriptor_4b8684575ab14afc) }

var fileDescriptor_4b8684575ab14afc = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x90, 0xcf, 0x4a, 0xfb, 0x40,
	0x10, 0x80, 0x49, 0xff, 0xa4, 0xed, 0xf6, 0x57, 0x7e, 0xb8, 0x50, 0x8c, 0x82, 0x10, 0x3d, 0x48,
	0x10, 0x4c, 0xa8, 0x3d, 0x88, 0x57, 0x0f, 0x42, 0x0f, 0x4a, 0x89, 0x78, 0xf1, 0x12, 0x36, 0xc9,
	0xb6, 0x59, 0xba, 0xd9, 0x0d, 0xb3, 0xbb, 0x82, 0x8f, 0xe7, 0xdb, 0xf8, 0x18, 0x92, 0x49, 0x72,
	0x9b, 0xf9, 0xbe, 0x8f, 0x39, 0x0c, 0x59, 0x37, 0xa0, 0xad, 0x2e, 0xb4, 0x4c, 0x0c, 0x67, 0x50,
	0x54, 0x31, 0xee, 0x74, 0x3e, 0xe0, 0x9b, 0x9f, 0x11, 0xf1, 0xdf, 0x51, 0xd1, 0x0d, 0x99, 0x35,
	0x92, 0x7d, 0x73, 0x30, 0x81, 0x17, 0x8e, 0xa3, 0xe5, 0xc3, 0x79, 0x3c, 0x64, 0x71, 0x97, 0xc4,
	0x7b, 0xf4, 0xe9, 0xd0, 0xd1, 0x0b, 0x32, 0xaf, 0x38, 0xe8, 0x4c, 0x94, 0x26, 0x18, 0x85, 0xe3,
	0x68, 0x92, 0xce, 0xda, 0x7d, 0x57, 0x9a, 0xcb, 0x5f, 0x8f, 0xf8, 0x5d, 0x4e, 0xaf, 0x08, 0x61,
	0x45, 0xa1, 0x9d, 0xb2, 0x99, 0x28, 0x03, 0x2f, 0xf4, 0xa2, 0x55, 0xba, 0xe8, 0xc9, 0xae, 0xa4,
	0x94, 0x4c, 0x14, 0xab, 0x79, 0x30, 0x0a, 0xbd, 0x68, 0x91, 0xe2, 0x4c, 0xaf, 0xc9, 0xbf, 0x86,
	0x83, 0xd1, 0x8a, 0x65, 0xe8, 0xc6, 0xe8, 0x96, 0x3d, 0x7b, 0x6b, 0x93, 0xf6, 0xea, 0x17, 0xb3,
	0x0c, 0x32, 0x07, 0x32, 0x98, 0x60, 0xb0, 0xe8, 0xc8, 0x07, 0x48, 0x7a, 0x47, 0xce, 0x7a, 0x5d,
	0xf3, 0x52, 0xb8, 0x1a, 0xab, 0x29, 0x56, 0xff, 0x3b, 0xf1, 0x8a, 0xbc, 0x6d, 0x6f, 0x49, 0x8f,
	0xb2, 0x83, 0x93, 0x12, 0x4b, 0x1f, 0xcb, 0x55, 0x87, 0x5f, 0x9c, 0x94, 0x6d, 0xb7, 0x26, 0xbe,
	0x30, 0x59, 0x03, 0x3a, 0x98, 0x85, 0x5e, 0x34, 0x4f, 0xa7, 0xc2, 0xec, 0x41, 0x3f, 0x3f, 0x7d,
	0x3e, 0x1e, 0x85, 0xad, 0x5c, 0x1e, 0x17, 0xba, 0x4e, 0x36, 0xdb, 0x53, 0xa2, 0xc4, 0xb1, 0xb2,
	0xf7, 0xc6, 0x32, 0x79, 0xe2, 0x90, 0x08, 0x65, 0x39, 0x28, 0x26, 0x13, 0x7c, 0x67, 0xee, 0x0e,
	0xc9, 0xf0, 0xd7, 0xdc, 0xc7, 0x69, 0xfb, 0x17, 0x00, 0x00, 0xff, 0xff, 0x77, 0xeb, 0xc0, 0x31,
	0xa8, 0x01, 0x00, 0x00,
}
