package common

const (
	TypeID                          = "ID"
	InterfaceModel                  = "Model"
	InterfaceRecord                 = "Record"
	InterfaceTable                  = "Table"
	InterfaceAssociation            = "Association"
	StructModelAssociation          = "ModelAssociation"
	ModelMethodName                 = "Name"
	ModelMethodTable                = "Table"
	ModelMethodRecordFactory        = "NewRecord"
	ModelMethodSlicePtrFactory      = "NewSlicePtr"
	ModelMethodRecordSliceCaster    = "AsRecordSlice"
	ModelMethodAssociations         = "Associations"
	ModelMethodAssociation          = "Association"
	RecordMethodModel               = "Model"
	RecordMethodAssignRecord        = "AssignRecord"
	RecordMethodAssignPartialRecord = "AssignPartialRecord"
	RecordMethodAssign              = "Assign"
	RecordMethodAssignPartial       = "AssignPartial"
	RecordMethodGetAssocPK          = "GetAssocPK"
	RecordMethodGetAssocFK          = "GetAssocFK"
	RecordMethodSetAssociated       = "SetAssociated"
	FmtTableVar                     = "%sTable"
	FmtModelVar                     = "%sModel"
	FmtModelVarAssociations         = "assoc%s"
	FmtModelStruct                  = "model%s"
	ErrInvalidSliceType             = "ErrInvalidSliceType"
	ErrNotAssociated                = "ErrNotAssociated"
	ErrInvalidRecord                = "ErrInvalidRecord"
	ErrInvalidAssociationRecord     = "ErrInvalidAssociationRecord"
)
