// Code generated by protoc-gen-go. DO NOT EDIT.
// source: collections.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CollectionOp int32

const (
	CollectionOp_REPLACE CollectionOp = 0
	CollectionOp_ADD     CollectionOp = 1
	CollectionOp_UPDATE  CollectionOp = 2
	CollectionOp_REMOVE  CollectionOp = 3
)

var CollectionOp_name = map[int32]string{
	0: "REPLACE",
	1: "ADD",
	2: "UPDATE",
	3: "REMOVE",
}

var CollectionOp_value = map[string]int32{
	"REPLACE": 0,
	"ADD":     1,
	"UPDATE":  2,
	"REMOVE":  3,
}

func (x CollectionOp) String() string {
	return proto.EnumName(CollectionOp_name, int32(x))
}

func (CollectionOp) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5da2d7d87b688bad, []int{0}
}

func init() {
	proto.RegisterEnum("protocol.CollectionOp", CollectionOp_name, CollectionOp_value)
}

func init() { proto.RegisterFile("collections.proto", fileDescriptor_5da2d7d87b688bad) }

var fileDescriptor_5da2d7d87b688bad = []byte{
	// 107 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0xce, 0xcf, 0xc9,
	0x49, 0x4d, 0x2e, 0xc9, 0xcc, 0xcf, 0x2b, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00,
	0x53, 0xc9, 0xf9, 0x39, 0x5a, 0x36, 0x5c, 0x3c, 0xce, 0x70, 0x69, 0xff, 0x02, 0x21, 0x6e, 0x2e,
	0xf6, 0x20, 0xd7, 0x00, 0x1f, 0x47, 0x67, 0x57, 0x01, 0x06, 0x21, 0x76, 0x2e, 0x66, 0x47, 0x17,
	0x17, 0x01, 0x46, 0x21, 0x2e, 0x2e, 0xb6, 0xd0, 0x00, 0x17, 0xc7, 0x10, 0x57, 0x01, 0x26, 0x10,
	0x3b, 0xc8, 0xd5, 0xd7, 0x3f, 0xcc, 0x55, 0x80, 0x39, 0x89, 0x0d, 0x6c, 0x8e, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0xcb, 0x2b, 0x68, 0xd1, 0x63, 0x00, 0x00, 0x00,
}
