// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hero.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Hero struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	LocalizedName        string   `protobuf:"bytes,3,opt,name=localized_name,json=localizedName,proto3" json:"localized_name,omitempty"`
	ImageFullUrl         string   `protobuf:"bytes,4,opt,name=image_full_url,json=imageFullUrl,proto3" json:"image_full_url,omitempty"`
	ImageLargeUrl        string   `protobuf:"bytes,5,opt,name=image_large_url,json=imageLargeUrl,proto3" json:"image_large_url,omitempty"`
	ImageSmallUrl        string   `protobuf:"bytes,6,opt,name=image_small_url,json=imageSmallUrl,proto3" json:"image_small_url,omitempty"`
	ImagePortraitUrl     string   `protobuf:"bytes,7,opt,name=image_portrait_url,json=imagePortraitUrl,proto3" json:"image_portrait_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hero) Reset()         { *m = Hero{} }
func (m *Hero) String() string { return proto.CompactTextString(m) }
func (*Hero) ProtoMessage()    {}
func (*Hero) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5c1be3f86b99613, []int{0}
}

func (m *Hero) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hero.Unmarshal(m, b)
}
func (m *Hero) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hero.Marshal(b, m, deterministic)
}
func (m *Hero) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hero.Merge(m, src)
}
func (m *Hero) XXX_Size() int {
	return xxx_messageInfo_Hero.Size(m)
}
func (m *Hero) XXX_DiscardUnknown() {
	xxx_messageInfo_Hero.DiscardUnknown(m)
}

var xxx_messageInfo_Hero proto.InternalMessageInfo

func (m *Hero) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Hero) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Hero) GetLocalizedName() string {
	if m != nil {
		return m.LocalizedName
	}
	return ""
}

func (m *Hero) GetImageFullUrl() string {
	if m != nil {
		return m.ImageFullUrl
	}
	return ""
}

func (m *Hero) GetImageLargeUrl() string {
	if m != nil {
		return m.ImageLargeUrl
	}
	return ""
}

func (m *Hero) GetImageSmallUrl() string {
	if m != nil {
		return m.ImageSmallUrl
	}
	return ""
}

func (m *Hero) GetImagePortraitUrl() string {
	if m != nil {
		return m.ImagePortraitUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*Hero)(nil), "protocol.Hero")
}

func init() { proto.RegisterFile("hero.proto", fileDescriptor_d5c1be3f86b99613) }

var fileDescriptor_d5c1be3f86b99613 = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0xd0, 0xc1, 0x8b, 0x82, 0x40,
	0x14, 0xc7, 0x71, 0xc6, 0x9d, 0x75, 0x77, 0x1f, 0xbb, 0xee, 0x32, 0x27, 0x8f, 0xb2, 0x54, 0x78,
	0x88, 0x2e, 0xfd, 0x0f, 0xd1, 0x21, 0x22, 0x0c, 0xcf, 0x32, 0xe9, 0x64, 0x03, 0xcf, 0x46, 0x5e,
	0x7a, 0xe9, 0xff, 0xee, 0x1e, 0xf3, 0x94, 0xa8, 0x93, 0xf2, 0xfd, 0x7d, 0x78, 0x87, 0x01, 0x38,
	0x19, 0x72, 0x8b, 0x96, 0x5c, 0xe7, 0xd4, 0x27, 0x7f, 0x4a, 0x87, 0xff, 0x37, 0x01, 0x72, 0x6d,
	0xc8, 0xa9, 0x08, 0x02, 0x5b, 0xc5, 0x22, 0x11, 0xa9, 0xcc, 0x02, 0x5b, 0x29, 0x05, 0xf2, 0xac,
	0x1b, 0x13, 0x07, 0x89, 0x48, 0xbf, 0x32, 0xfe, 0x57, 0x53, 0x88, 0xd0, 0x95, 0x1a, 0xed, 0xd5,
	0x54, 0x05, 0xaf, 0x6f, 0xbc, 0xfe, 0x3c, 0xea, 0xd6, 0xb3, 0x09, 0x44, 0xb6, 0xd1, 0xb5, 0x29,
	0x8e, 0x3d, 0x62, 0xd1, 0x13, 0xc6, 0x92, 0xd9, 0x37, 0xd7, 0x55, 0x8f, 0x98, 0x13, 0xaa, 0x19,
	0xfc, 0x0e, 0x0a, 0x35, 0xd5, 0x86, 0xd9, 0xfb, 0x70, 0x8d, 0xf3, 0xc6, 0xd7, 0x17, 0x77, 0x69,
	0xf4, 0x78, 0x2e, 0x7c, 0x72, 0x7b, 0x5f, 0xbd, 0x9b, 0x83, 0x1a, 0x5c, 0xeb, 0xa8, 0x23, 0x6d,
	0x3b, 0xa6, 0x1f, 0x4c, 0xff, 0x78, 0xd9, 0x8d, 0x43, 0x4e, 0x78, 0x08, 0xf9, 0x05, 0x96, 0xf7,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x2d, 0xa8, 0xef, 0xd3, 0x16, 0x01, 0x00, 0x00,
}
