// Code generated by protoc-gen-go. DO NOT EDIT.
// source: live_matches.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LiveMatches struct {
	Matches              []*LiveMatch `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *LiveMatches) Reset()         { *m = LiveMatches{} }
func (m *LiveMatches) String() string { return proto.CompactTextString(m) }
func (*LiveMatches) ProtoMessage()    {}
func (*LiveMatches) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd3315530c804664, []int{0}
}

func (m *LiveMatches) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LiveMatches.Unmarshal(m, b)
}
func (m *LiveMatches) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LiveMatches.Marshal(b, m, deterministic)
}
func (m *LiveMatches) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiveMatches.Merge(m, src)
}
func (m *LiveMatches) XXX_Size() int {
	return xxx_messageInfo_LiveMatches.Size(m)
}
func (m *LiveMatches) XXX_DiscardUnknown() {
	xxx_messageInfo_LiveMatches.DiscardUnknown(m)
}

var xxx_messageInfo_LiveMatches proto.InternalMessageInfo

func (m *LiveMatches) GetMatches() []*LiveMatch {
	if m != nil {
		return m.Matches
	}
	return nil
}

type LiveMatchesChange struct {
	Op                   CollectionOp `protobuf:"varint,1,opt,name=op,proto3,enum=protocol.CollectionOp" json:"op,omitempty"`
	Change               *LiveMatches `protobuf:"bytes,2,opt,name=change,proto3" json:"change,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *LiveMatchesChange) Reset()         { *m = LiveMatchesChange{} }
func (m *LiveMatchesChange) String() string { return proto.CompactTextString(m) }
func (*LiveMatchesChange) ProtoMessage()    {}
func (*LiveMatchesChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd3315530c804664, []int{1}
}

func (m *LiveMatchesChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LiveMatchesChange.Unmarshal(m, b)
}
func (m *LiveMatchesChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LiveMatchesChange.Marshal(b, m, deterministic)
}
func (m *LiveMatchesChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiveMatchesChange.Merge(m, src)
}
func (m *LiveMatchesChange) XXX_Size() int {
	return xxx_messageInfo_LiveMatchesChange.Size(m)
}
func (m *LiveMatchesChange) XXX_DiscardUnknown() {
	xxx_messageInfo_LiveMatchesChange.DiscardUnknown(m)
}

var xxx_messageInfo_LiveMatchesChange proto.InternalMessageInfo

func (m *LiveMatchesChange) GetOp() CollectionOp {
	if m != nil {
		return m.Op
	}
	return CollectionOp_REPLACE
}

func (m *LiveMatchesChange) GetChange() *LiveMatches {
	if m != nil {
		return m.Change
	}
	return nil
}

func init() {
	proto.RegisterType((*LiveMatches)(nil), "protocol.LiveMatches")
	proto.RegisterType((*LiveMatchesChange)(nil), "protocol.LiveMatchesChange")
}

func init() { proto.RegisterFile("live_matches.proto", fileDescriptor_dd3315530c804664) }

var fileDescriptor_dd3315530c804664 = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xca, 0xc9, 0x2c, 0x4b,
	0x8d, 0xcf, 0x4d, 0x2c, 0x49, 0xce, 0x48, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2,
	0x00, 0x53, 0xc9, 0xf9, 0x39, 0x52, 0x02, 0x08, 0x59, 0x88, 0x9c, 0x94, 0x60, 0x72, 0x7e, 0x4e,
	0x4e, 0x6a, 0x72, 0x49, 0x66, 0x7e, 0x1e, 0x54, 0xb9, 0x92, 0x0d, 0x17, 0xb7, 0x4f, 0x66, 0x59,
	0xaa, 0x2f, 0xc4, 0x0c, 0x21, 0x5d, 0x2e, 0x76, 0xa8, 0x71, 0x12, 0x8c, 0x0a, 0xcc, 0x1a, 0xdc,
	0x46, 0xc2, 0x7a, 0x30, 0xf3, 0xf4, 0xe0, 0xea, 0x82, 0x60, 0x6a, 0x94, 0xb2, 0xb8, 0x04, 0x91,
	0x74, 0x3b, 0x67, 0x24, 0xe6, 0xa5, 0xa7, 0x0a, 0xa9, 0x71, 0x31, 0xe5, 0x17, 0x48, 0x30, 0x2a,
	0x30, 0x6a, 0xf0, 0x19, 0x89, 0x21, 0xb4, 0x3b, 0xc3, 0xed, 0xf6, 0x2f, 0x08, 0x62, 0xca, 0x2f,
	0x10, 0xd2, 0xe5, 0x62, 0x4b, 0x06, 0xeb, 0x90, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x36, 0x12, 0xc5,
	0x62, 0x55, 0x6a, 0x71, 0x10, 0x54, 0x51, 0x12, 0x1b, 0x58, 0xd6, 0x18, 0x10, 0x00, 0x00, 0xff,
	0xff, 0xb7, 0x95, 0xe0, 0x83, 0xf5, 0x00, 0x00, 0x00,
}
