// Code generated by protoc-gen-go. DO NOT EDIT.
// source: live_matches.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LiveMatchesChange_Op int32

const (
	LiveMatchesChange_REPLACE LiveMatchesChange_Op = 0
	LiveMatchesChange_ADD     LiveMatchesChange_Op = 1
	LiveMatchesChange_UPDATE  LiveMatchesChange_Op = 2
	LiveMatchesChange_REMOVE  LiveMatchesChange_Op = 3
)

var LiveMatchesChange_Op_name = map[int32]string{
	0: "REPLACE",
	1: "ADD",
	2: "UPDATE",
	3: "REMOVE",
}

var LiveMatchesChange_Op_value = map[string]int32{
	"REPLACE": 0,
	"ADD":     1,
	"UPDATE":  2,
	"REMOVE":  3,
}

func (x LiveMatchesChange_Op) String() string {
	return proto.EnumName(LiveMatchesChange_Op_name, int32(x))
}

func (LiveMatchesChange_Op) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dd3315530c804664, []int{1, 0}
}

type LiveMatches struct {
	Matches              []*LiveMatch `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *LiveMatches) Reset()         { *m = LiveMatches{} }
func (m *LiveMatches) String() string { return proto.CompactTextString(m) }
func (*LiveMatches) ProtoMessage()    {}
func (*LiveMatches) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd3315530c804664, []int{0}
}

func (m *LiveMatches) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LiveMatches.Unmarshal(m, b)
}
func (m *LiveMatches) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LiveMatches.Marshal(b, m, deterministic)
}
func (m *LiveMatches) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiveMatches.Merge(m, src)
}
func (m *LiveMatches) XXX_Size() int {
	return xxx_messageInfo_LiveMatches.Size(m)
}
func (m *LiveMatches) XXX_DiscardUnknown() {
	xxx_messageInfo_LiveMatches.DiscardUnknown(m)
}

var xxx_messageInfo_LiveMatches proto.InternalMessageInfo

func (m *LiveMatches) GetMatches() []*LiveMatch {
	if m != nil {
		return m.Matches
	}
	return nil
}

type LiveMatchesChange struct {
	Op                   LiveMatchesChange_Op `protobuf:"varint,1,opt,name=op,proto3,enum=protocol.LiveMatchesChange_Op" json:"op,omitempty"`
	Change               *LiveMatches         `protobuf:"bytes,2,opt,name=change,proto3" json:"change,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *LiveMatchesChange) Reset()         { *m = LiveMatchesChange{} }
func (m *LiveMatchesChange) String() string { return proto.CompactTextString(m) }
func (*LiveMatchesChange) ProtoMessage()    {}
func (*LiveMatchesChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd3315530c804664, []int{1}
}

func (m *LiveMatchesChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LiveMatchesChange.Unmarshal(m, b)
}
func (m *LiveMatchesChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LiveMatchesChange.Marshal(b, m, deterministic)
}
func (m *LiveMatchesChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiveMatchesChange.Merge(m, src)
}
func (m *LiveMatchesChange) XXX_Size() int {
	return xxx_messageInfo_LiveMatchesChange.Size(m)
}
func (m *LiveMatchesChange) XXX_DiscardUnknown() {
	xxx_messageInfo_LiveMatchesChange.DiscardUnknown(m)
}

var xxx_messageInfo_LiveMatchesChange proto.InternalMessageInfo

func (m *LiveMatchesChange) GetOp() LiveMatchesChange_Op {
	if m != nil {
		return m.Op
	}
	return LiveMatchesChange_REPLACE
}

func (m *LiveMatchesChange) GetChange() *LiveMatches {
	if m != nil {
		return m.Change
	}
	return nil
}

func init() {
	proto.RegisterEnum("protocol.LiveMatchesChange_Op", LiveMatchesChange_Op_name, LiveMatchesChange_Op_value)
	proto.RegisterType((*LiveMatches)(nil), "protocol.LiveMatches")
	proto.RegisterType((*LiveMatchesChange)(nil), "protocol.LiveMatchesChange")
}

func init() { proto.RegisterFile("live_matches.proto", fileDescriptor_dd3315530c804664) }

var fileDescriptor_dd3315530c804664 = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xca, 0xc9, 0x2c, 0x4b,
	0x8d, 0xcf, 0x4d, 0x2c, 0x49, 0xce, 0x48, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2,
	0x00, 0x53, 0xc9, 0xf9, 0x39, 0x52, 0x02, 0x08, 0x59, 0x88, 0x9c, 0x92, 0x0d, 0x17, 0xb7, 0x4f,
	0x66, 0x59, 0xaa, 0x2f, 0x44, 0x83, 0x90, 0x2e, 0x17, 0x3b, 0x54, 0xaf, 0x04, 0xa3, 0x02, 0xb3,
	0x06, 0xb7, 0x91, 0xb0, 0x1e, 0x4c, 0xb3, 0x1e, 0x5c, 0x5d, 0x10, 0x4c, 0x8d, 0xd2, 0x32, 0x46,
	0x2e, 0x41, 0x24, 0xed, 0xce, 0x19, 0x89, 0x79, 0xe9, 0xa9, 0x42, 0x7a, 0x5c, 0x4c, 0xf9, 0x05,
	0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x7c, 0x46, 0x72, 0x58, 0xf4, 0xc3, 0x14, 0xea, 0xf9, 0x17, 0x04,
	0x31, 0xe5, 0x17, 0x08, 0xe9, 0x72, 0xb1, 0x25, 0x83, 0x05, 0x24, 0x98, 0x14, 0x18, 0x35, 0xb8,
	0x8d, 0x44, 0xb1, 0xea, 0x09, 0x82, 0x2a, 0x52, 0x32, 0xe2, 0x62, 0xf2, 0x2f, 0x10, 0xe2, 0xe6,
	0x62, 0x0f, 0x72, 0x0d, 0xf0, 0x71, 0x74, 0x76, 0x15, 0x60, 0x10, 0x62, 0xe7, 0x62, 0x76, 0x74,
	0x71, 0x11, 0x60, 0x14, 0xe2, 0xe2, 0x62, 0x0b, 0x0d, 0x70, 0x71, 0x0c, 0x71, 0x15, 0x60, 0x02,
	0xb1, 0x83, 0x5c, 0x7d, 0xfd, 0xc3, 0x5c, 0x05, 0x98, 0x93, 0xd8, 0xc0, 0x26, 0x1a, 0x03, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x37, 0xdf, 0x4a, 0xf1, 0x1f, 0x01, 0x00, 0x00,
}
