// Code generated by protoc-gen-go. DO NOT EDIT.
// source: player.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Player struct {
	AccountId            uint32          `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Name                 string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PersonaName          string          `protobuf:"bytes,3,opt,name=persona_name,json=personaName,proto3" json:"persona_name,omitempty"`
	AvatarUrl            string          `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	AvatarMediumUrl      string          `protobuf:"bytes,5,opt,name=avatar_medium_url,json=avatarMediumUrl,proto3" json:"avatar_medium_url,omitempty"`
	AvatarFullUrl        string          `protobuf:"bytes,6,opt,name=avatar_full_url,json=avatarFullUrl,proto3" json:"avatar_full_url,omitempty"`
	IsPro                bool            `protobuf:"varint,7,opt,name=is_pro,json=isPro,proto3" json:"is_pro,omitempty"`
	Team                 *Player_Team    `protobuf:"bytes,100,opt,name=team,proto3" json:"team,omitempty"`
	Matches              []*Player_Match `protobuf:"bytes,101,rep,name=matches,proto3" json:"matches,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{0}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetAccountId() uint32 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *Player) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Player) GetPersonaName() string {
	if m != nil {
		return m.PersonaName
	}
	return ""
}

func (m *Player) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *Player) GetAvatarMediumUrl() string {
	if m != nil {
		return m.AvatarMediumUrl
	}
	return ""
}

func (m *Player) GetAvatarFullUrl() string {
	if m != nil {
		return m.AvatarFullUrl
	}
	return ""
}

func (m *Player) GetIsPro() bool {
	if m != nil {
		return m.IsPro
	}
	return false
}

func (m *Player) GetTeam() *Player_Team {
	if m != nil {
		return m.Team
	}
	return nil
}

func (m *Player) GetMatches() []*Player_Match {
	if m != nil {
		return m.Matches
	}
	return nil
}

type Player_Match struct {
	MatchId              uint64                      `protobuf:"varint,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	LobbyId              uint64                      `protobuf:"varint,2,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	LobbyType            LobbyType                   `protobuf:"varint,3,opt,name=lobby_type,json=lobbyType,proto3,enum=protocol.LobbyType" json:"lobby_type,omitempty"`
	LeagueId             uint64                      `protobuf:"varint,4,opt,name=league_id,json=leagueId,proto3" json:"league_id,omitempty"`
	SeriesId             uint64                      `protobuf:"varint,5,opt,name=series_id,json=seriesId,proto3" json:"series_id,omitempty"`
	GameMode             GameMode                    `protobuf:"varint,6,opt,name=game_mode,json=gameMode,proto3,enum=protocol.GameMode" json:"game_mode,omitempty"`
	AverageMmr           uint32                      `protobuf:"varint,7,opt,name=average_mmr,json=averageMmr,proto3" json:"average_mmr,omitempty"`
	RadiantTeamId        uint64                      `protobuf:"varint,8,opt,name=radiant_team_id,json=radiantTeamId,proto3" json:"radiant_team_id,omitempty"`
	RadiantTeamName      string                      `protobuf:"bytes,9,opt,name=radiant_team_name,json=radiantTeamName,proto3" json:"radiant_team_name,omitempty"`
	RadiantTeamTag       string                      `protobuf:"bytes,10,opt,name=radiant_team_tag,json=radiantTeamTag,proto3" json:"radiant_team_tag,omitempty"`
	RadiantTeamLogo      uint64                      `protobuf:"varint,11,opt,name=radiant_team_logo,json=radiantTeamLogo,proto3" json:"radiant_team_logo,omitempty"`
	RadiantTeamLogoUrl   string                      `protobuf:"bytes,12,opt,name=radiant_team_logo_url,json=radiantTeamLogoUrl,proto3" json:"radiant_team_logo_url,omitempty"`
	DireTeamId           uint64                      `protobuf:"varint,13,opt,name=dire_team_id,json=direTeamId,proto3" json:"dire_team_id,omitempty"`
	DireTeamName         string                      `protobuf:"bytes,14,opt,name=dire_team_name,json=direTeamName,proto3" json:"dire_team_name,omitempty"`
	DireTeamTag          string                      `protobuf:"bytes,15,opt,name=dire_team_tag,json=direTeamTag,proto3" json:"dire_team_tag,omitempty"`
	DireTeamLogo         uint64                      `protobuf:"varint,16,opt,name=dire_team_logo,json=direTeamLogo,proto3" json:"dire_team_logo,omitempty"`
	DireTeamLogoUrl      string                      `protobuf:"bytes,17,opt,name=dire_team_logo_url,json=direTeamLogoUrl,proto3" json:"dire_team_logo_url,omitempty"`
	ActivateTime         *timestamp.Timestamp        `protobuf:"bytes,18,opt,name=activate_time,json=activateTime,proto3" json:"activate_time,omitempty"`
	DeactivateTime       *timestamp.Timestamp        `protobuf:"bytes,19,opt,name=deactivate_time,json=deactivateTime,proto3" json:"deactivate_time,omitempty"`
	LastUpdateTime       *timestamp.Timestamp        `protobuf:"bytes,20,opt,name=last_update_time,json=lastUpdateTime,proto3" json:"last_update_time,omitempty"`
	StartTime            *timestamp.Timestamp        `protobuf:"bytes,21,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	SeriesType           uint32                      `protobuf:"varint,22,opt,name=series_type,json=seriesType,proto3" json:"series_type,omitempty"`
	SeriesGame           uint32                      `protobuf:"varint,23,opt,name=series_game,json=seriesGame,proto3" json:"series_game,omitempty"`
	Duration             uint32                      `protobuf:"varint,24,opt,name=duration,proto3" json:"duration,omitempty"`
	RadiantScore         uint32                      `protobuf:"varint,25,opt,name=radiant_score,json=radiantScore,proto3" json:"radiant_score,omitempty"`
	DireScore            uint32                      `protobuf:"varint,26,opt,name=dire_score,json=direScore,proto3" json:"dire_score,omitempty"`
	Outcome              MatchOutcome                `protobuf:"varint,27,opt,name=outcome,proto3,enum=protocol.MatchOutcome" json:"outcome,omitempty"`
	PlayerDetails        *Player_Match_PlayerDetails `protobuf:"bytes,100,opt,name=player_details,json=playerDetails,proto3" json:"player_details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *Player_Match) Reset()         { *m = Player_Match{} }
func (m *Player_Match) String() string { return proto.CompactTextString(m) }
func (*Player_Match) ProtoMessage()    {}
func (*Player_Match) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{0, 0}
}

func (m *Player_Match) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player_Match.Unmarshal(m, b)
}
func (m *Player_Match) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player_Match.Marshal(b, m, deterministic)
}
func (m *Player_Match) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player_Match.Merge(m, src)
}
func (m *Player_Match) XXX_Size() int {
	return xxx_messageInfo_Player_Match.Size(m)
}
func (m *Player_Match) XXX_DiscardUnknown() {
	xxx_messageInfo_Player_Match.DiscardUnknown(m)
}

var xxx_messageInfo_Player_Match proto.InternalMessageInfo

func (m *Player_Match) GetMatchId() uint64 {
	if m != nil {
		return m.MatchId
	}
	return 0
}

func (m *Player_Match) GetLobbyId() uint64 {
	if m != nil {
		return m.LobbyId
	}
	return 0
}

func (m *Player_Match) GetLobbyType() LobbyType {
	if m != nil {
		return m.LobbyType
	}
	return LobbyType_LOBBY_TYPE_CASUAL_MATCH
}

func (m *Player_Match) GetLeagueId() uint64 {
	if m != nil {
		return m.LeagueId
	}
	return 0
}

func (m *Player_Match) GetSeriesId() uint64 {
	if m != nil {
		return m.SeriesId
	}
	return 0
}

func (m *Player_Match) GetGameMode() GameMode {
	if m != nil {
		return m.GameMode
	}
	return GameMode_GAME_MODE_NONE
}

func (m *Player_Match) GetAverageMmr() uint32 {
	if m != nil {
		return m.AverageMmr
	}
	return 0
}

func (m *Player_Match) GetRadiantTeamId() uint64 {
	if m != nil {
		return m.RadiantTeamId
	}
	return 0
}

func (m *Player_Match) GetRadiantTeamName() string {
	if m != nil {
		return m.RadiantTeamName
	}
	return ""
}

func (m *Player_Match) GetRadiantTeamTag() string {
	if m != nil {
		return m.RadiantTeamTag
	}
	return ""
}

func (m *Player_Match) GetRadiantTeamLogo() uint64 {
	if m != nil {
		return m.RadiantTeamLogo
	}
	return 0
}

func (m *Player_Match) GetRadiantTeamLogoUrl() string {
	if m != nil {
		return m.RadiantTeamLogoUrl
	}
	return ""
}

func (m *Player_Match) GetDireTeamId() uint64 {
	if m != nil {
		return m.DireTeamId
	}
	return 0
}

func (m *Player_Match) GetDireTeamName() string {
	if m != nil {
		return m.DireTeamName
	}
	return ""
}

func (m *Player_Match) GetDireTeamTag() string {
	if m != nil {
		return m.DireTeamTag
	}
	return ""
}

func (m *Player_Match) GetDireTeamLogo() uint64 {
	if m != nil {
		return m.DireTeamLogo
	}
	return 0
}

func (m *Player_Match) GetDireTeamLogoUrl() string {
	if m != nil {
		return m.DireTeamLogoUrl
	}
	return ""
}

func (m *Player_Match) GetActivateTime() *timestamp.Timestamp {
	if m != nil {
		return m.ActivateTime
	}
	return nil
}

func (m *Player_Match) GetDeactivateTime() *timestamp.Timestamp {
	if m != nil {
		return m.DeactivateTime
	}
	return nil
}

func (m *Player_Match) GetLastUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdateTime
	}
	return nil
}

func (m *Player_Match) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *Player_Match) GetSeriesType() uint32 {
	if m != nil {
		return m.SeriesType
	}
	return 0
}

func (m *Player_Match) GetSeriesGame() uint32 {
	if m != nil {
		return m.SeriesGame
	}
	return 0
}

func (m *Player_Match) GetDuration() uint32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Player_Match) GetRadiantScore() uint32 {
	if m != nil {
		return m.RadiantScore
	}
	return 0
}

func (m *Player_Match) GetDireScore() uint32 {
	if m != nil {
		return m.DireScore
	}
	return 0
}

func (m *Player_Match) GetOutcome() MatchOutcome {
	if m != nil {
		return m.Outcome
	}
	return MatchOutcome_MATCH_OUTCOME_UNKNOWN
}

func (m *Player_Match) GetPlayerDetails() *Player_Match_PlayerDetails {
	if m != nil {
		return m.PlayerDetails
	}
	return nil
}

type Player_Match_PlayerDetails struct {
	HeroId               uint64   `protobuf:"varint,1,opt,name=hero_id,json=heroId,proto3" json:"hero_id,omitempty"`
	PlayerSlot           uint32   `protobuf:"varint,2,opt,name=player_slot,json=playerSlot,proto3" json:"player_slot,omitempty"`
	ProName              string   `protobuf:"bytes,3,opt,name=pro_name,json=proName,proto3" json:"pro_name,omitempty"`
	Kills                uint32   `protobuf:"varint,4,opt,name=kills,proto3" json:"kills,omitempty"`
	Deaths               uint32   `protobuf:"varint,5,opt,name=deaths,proto3" json:"deaths,omitempty"`
	Assists              uint32   `protobuf:"varint,6,opt,name=assists,proto3" json:"assists,omitempty"`
	Items                []int64  `protobuf:"varint,7,rep,packed,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player_Match_PlayerDetails) Reset()         { *m = Player_Match_PlayerDetails{} }
func (m *Player_Match_PlayerDetails) String() string { return proto.CompactTextString(m) }
func (*Player_Match_PlayerDetails) ProtoMessage()    {}
func (*Player_Match_PlayerDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{0, 0, 0}
}

func (m *Player_Match_PlayerDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player_Match_PlayerDetails.Unmarshal(m, b)
}
func (m *Player_Match_PlayerDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player_Match_PlayerDetails.Marshal(b, m, deterministic)
}
func (m *Player_Match_PlayerDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player_Match_PlayerDetails.Merge(m, src)
}
func (m *Player_Match_PlayerDetails) XXX_Size() int {
	return xxx_messageInfo_Player_Match_PlayerDetails.Size(m)
}
func (m *Player_Match_PlayerDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_Player_Match_PlayerDetails.DiscardUnknown(m)
}

var xxx_messageInfo_Player_Match_PlayerDetails proto.InternalMessageInfo

func (m *Player_Match_PlayerDetails) GetHeroId() uint64 {
	if m != nil {
		return m.HeroId
	}
	return 0
}

func (m *Player_Match_PlayerDetails) GetPlayerSlot() uint32 {
	if m != nil {
		return m.PlayerSlot
	}
	return 0
}

func (m *Player_Match_PlayerDetails) GetProName() string {
	if m != nil {
		return m.ProName
	}
	return ""
}

func (m *Player_Match_PlayerDetails) GetKills() uint32 {
	if m != nil {
		return m.Kills
	}
	return 0
}

func (m *Player_Match_PlayerDetails) GetDeaths() uint32 {
	if m != nil {
		return m.Deaths
	}
	return 0
}

func (m *Player_Match_PlayerDetails) GetAssists() uint32 {
	if m != nil {
		return m.Assists
	}
	return 0
}

func (m *Player_Match_PlayerDetails) GetItems() []int64 {
	if m != nil {
		return m.Items
	}
	return nil
}

type Player_Team struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tag                  string   `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	LogoUrl              string   `protobuf:"bytes,4,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player_Team) Reset()         { *m = Player_Team{} }
func (m *Player_Team) String() string { return proto.CompactTextString(m) }
func (*Player_Team) ProtoMessage()    {}
func (*Player_Team) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{0, 1}
}

func (m *Player_Team) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player_Team.Unmarshal(m, b)
}
func (m *Player_Team) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player_Team.Marshal(b, m, deterministic)
}
func (m *Player_Team) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player_Team.Merge(m, src)
}
func (m *Player_Team) XXX_Size() int {
	return xxx_messageInfo_Player_Team.Size(m)
}
func (m *Player_Team) XXX_DiscardUnknown() {
	xxx_messageInfo_Player_Team.DiscardUnknown(m)
}

var xxx_messageInfo_Player_Team proto.InternalMessageInfo

func (m *Player_Team) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Player_Team) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Player_Team) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *Player_Team) GetLogoUrl() string {
	if m != nil {
		return m.LogoUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*Player)(nil), "protocol.Player")
	proto.RegisterType((*Player_Match)(nil), "protocol.Player.Match")
	proto.RegisterType((*Player_Match_PlayerDetails)(nil), "protocol.Player.Match.PlayerDetails")
	proto.RegisterType((*Player_Team)(nil), "protocol.Player.Team")
}

func init() { proto.RegisterFile("player.proto", fileDescriptor_41d803d1b635d5c6) }

var fileDescriptor_41d803d1b635d5c6 = []byte{
	// 884 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x55, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x86, 0xac, 0xff, 0x91, 0x48, 0x3b, 0x9b, 0xd8, 0x61, 0x14, 0x14, 0x56, 0xd3, 0xa0, 0x50,
	0x5b, 0x40, 0x4e, 0xd5, 0x53, 0x4f, 0x3d, 0x34, 0x68, 0x21, 0x34, 0x6e, 0x03, 0xc6, 0x41, 0x8f,
	0xc4, 0x5a, 0xbb, 0xa1, 0x89, 0xee, 0x6a, 0x89, 0xdd, 0xa5, 0x01, 0xbd, 0x40, 0x5f, 0xa5, 0xef,
	0xd1, 0x27, 0x2b, 0x66, 0x96, 0x94, 0xa8, 0x3a, 0x80, 0x4f, 0xe2, 0x7c, 0xf3, 0xed, 0xb7, 0x9a,
	0xe1, 0xcc, 0x47, 0x98, 0x96, 0x8a, 0xef, 0xa4, 0x5d, 0x96, 0xd6, 0x78, 0xc3, 0x46, 0xf4, 0xb3,
	0x31, 0x6a, 0x76, 0x99, 0x1b, 0x93, 0x2b, 0x79, 0x45, 0xc0, 0x6d, 0xf5, 0xe9, 0xca, 0x17, 0x5a,
	0x3a, 0xcf, 0x75, 0x19, 0xa8, 0xb3, 0x89, 0xdc, 0x56, 0xda, 0x85, 0xe0, 0xd5, 0x3f, 0x31, 0x0c,
	0xde, 0x93, 0x10, 0xfb, 0x02, 0x80, 0x6f, 0x36, 0xa6, 0xda, 0xfa, 0xac, 0x10, 0x49, 0x67, 0xde,
	0x59, 0x44, 0xe9, 0xb8, 0x46, 0xd6, 0x82, 0x31, 0xe8, 0x6d, 0xb9, 0x96, 0xc9, 0xc9, 0xbc, 0xb3,
	0x18, 0xa7, 0xf4, 0xcc, 0xbe, 0x84, 0x69, 0x29, 0xad, 0x33, 0x5b, 0x9e, 0x51, 0xae, 0x4b, 0xb9,
	0x49, 0x8d, 0xfd, 0x8e, 0x14, 0x54, 0xbd, 0xe7, 0x9e, 0xdb, 0xac, 0xb2, 0x2a, 0xe9, 0x11, 0x61,
	0x1c, 0x90, 0x8f, 0x56, 0xb1, 0x6f, 0xe1, 0x49, 0x9d, 0xd6, 0x52, 0x14, 0x95, 0x26, 0x56, 0x9f,
	0x58, 0xa7, 0x21, 0x71, 0x4d, 0x38, 0x72, 0xbf, 0x86, 0x1a, 0xca, 0x3e, 0x55, 0x4a, 0x11, 0x73,
	0x40, 0xcc, 0x28, 0xc0, 0xbf, 0x54, 0x4a, 0x21, 0xef, 0x1c, 0x06, 0x85, 0xcb, 0x4a, 0x6b, 0x92,
	0xe1, 0xbc, 0xb3, 0x18, 0xa5, 0xfd, 0xc2, 0xbd, 0xb7, 0x86, 0x7d, 0x03, 0x3d, 0x2f, 0xb9, 0x4e,
	0xc4, 0xbc, 0xb3, 0x98, 0xac, 0xce, 0x97, 0x4d, 0xc7, 0x96, 0xa1, 0xfe, 0xe5, 0x8d, 0xe4, 0x3a,
	0x25, 0x0a, 0x7b, 0x03, 0x43, 0xcd, 0xfd, 0xe6, 0x4e, 0xba, 0x44, 0xce, 0xbb, 0x8b, 0xc9, 0xea,
	0xe2, 0x01, 0xfb, 0x1a, 0xf3, 0x69, 0x43, 0x9b, 0xfd, 0x3d, 0x81, 0x3e, 0x41, 0xec, 0x05, 0x8c,
	0x08, 0x6c, 0x9a, 0xd8, 0xab, 0x49, 0x6b, 0x81, 0x29, 0x65, 0x6e, 0x6f, 0x77, 0x98, 0x3a, 0x09,
	0x29, 0x8a, 0xd7, 0x82, 0xad, 0x00, 0x42, 0xca, 0xef, 0xca, 0xd0, 0xc7, 0x78, 0xf5, 0xf4, 0x70,
	0xe9, 0x3b, 0xcc, 0xdd, 0xec, 0x4a, 0x99, 0x8e, 0x55, 0xf3, 0xc8, 0x5e, 0xc2, 0x58, 0x49, 0x9e,
	0x57, 0x12, 0xf5, 0x7a, 0xa4, 0x37, 0x0a, 0xc0, 0x5a, 0x60, 0xd2, 0x49, 0x5b, 0x48, 0x87, 0xc9,
	0x7e, 0x48, 0x06, 0x60, 0x2d, 0xd8, 0x15, 0x8c, 0x73, 0xae, 0x65, 0xa6, 0x8d, 0x90, 0xd4, 0xc3,
	0x78, 0xc5, 0x0e, 0x97, 0xfd, 0xca, 0xb5, 0xbc, 0x36, 0x42, 0xa6, 0xa3, 0xbc, 0x7e, 0x62, 0x97,
	0x30, 0xe1, 0xf7, 0xd2, 0xf2, 0x5c, 0x66, 0x5a, 0x5b, 0xea, 0x6b, 0x94, 0x42, 0x0d, 0x5d, 0x6b,
	0x8b, 0xef, 0xc6, 0x72, 0x51, 0xf0, 0xad, 0xcf, 0xb0, 0x83, 0x78, 0xe9, 0x88, 0x2e, 0x8d, 0x6a,
	0x18, 0xbb, 0xbb, 0x16, 0xf8, 0xbe, 0x8f, 0x78, 0x34, 0x36, 0xe3, 0xf0, 0xbe, 0x5b, 0x4c, 0x1a,
	0x9d, 0x05, 0x9c, 0x1d, 0x71, 0x3d, 0xcf, 0x13, 0x20, 0x6a, 0xdc, 0xa2, 0xde, 0xf0, 0xfc, 0x81,
	0xaa, 0x32, 0xb9, 0x49, 0x26, 0x74, 0x7f, 0x5b, 0xf5, 0x9d, 0xc9, 0x0d, 0xfb, 0x1e, 0xce, 0x1f,
	0x70, 0x69, 0x96, 0xa6, 0x24, 0xcd, 0xfe, 0xc7, 0xc7, 0x81, 0x9a, 0xc3, 0x54, 0x14, 0x56, 0xee,
	0x2b, 0x8b, 0x48, 0x19, 0x10, 0xab, 0xcb, 0x7a, 0x0d, 0xf1, 0x81, 0x41, 0x35, 0xc5, 0xa4, 0x36,
	0x6d, 0x38, 0x54, 0xd0, 0x2b, 0x88, 0x0e, 0x2c, 0xac, 0xe6, 0x34, 0xec, 0x4b, 0x43, 0xc2, 0x52,
	0x8e, 0x94, 0xa8, 0x8e, 0x33, 0xba, 0x6d, 0xaf, 0x44, 0x45, 0x7c, 0x07, 0xec, 0x98, 0x45, 0x15,
	0x3c, 0x09, 0x7d, 0x6c, 0x33, 0xf1, 0xef, 0xff, 0x04, 0x11, 0xdf, 0xf8, 0xe2, 0x9e, 0x7b, 0x99,
	0xa1, 0x19, 0x24, 0x8c, 0x36, 0x60, 0xb6, 0x0c, 0x4e, 0xb1, 0x6c, 0x9c, 0x62, 0x79, 0xd3, 0x38,
	0x45, 0x3a, 0x6d, 0x0e, 0x20, 0xc4, 0x7e, 0x86, 0x53, 0x21, 0x8f, 0x25, 0x9e, 0x3e, 0x2a, 0x11,
	0x1f, 0x8e, 0x90, 0xc8, 0x5b, 0x38, 0x53, 0xdc, 0xf9, 0xac, 0x2a, 0xc5, 0x5e, 0xe5, 0xd9, 0xe3,
	0x2a, 0x78, 0xe6, 0x23, 0x1d, 0x21, 0x95, 0x1f, 0x01, 0x9c, 0xe7, 0xd6, 0x87, 0xf3, 0xe7, 0x8f,
	0x9e, 0x1f, 0x13, 0x9b, 0x8e, 0x5e, 0xc2, 0xa4, 0xde, 0x08, 0xda, 0xb1, 0x8b, 0x30, 0xc3, 0x01,
	0xa2, 0x7d, 0x3a, 0x10, 0x70, 0xee, 0x93, 0xe7, 0x6d, 0x02, 0xee, 0x04, 0x9b, 0xc1, 0x48, 0x54,
	0x96, 0xfb, 0xc2, 0x6c, 0x93, 0x84, 0xb2, 0xfb, 0x98, 0x7d, 0x05, 0xcd, 0xa4, 0x67, 0x6e, 0x63,
	0xac, 0x4c, 0x5e, 0x10, 0x61, 0x5a, 0x83, 0x1f, 0x10, 0x43, 0x33, 0xa4, 0xd7, 0x16, 0x18, 0xb3,
	0x60, 0xb1, 0x88, 0x84, 0xf4, 0x1b, 0x18, 0x9a, 0xca, 0x6f, 0x8c, 0x96, 0xc9, 0x4b, 0x5a, 0xca,
	0x96, 0xed, 0x90, 0xb9, 0xfc, 0x11, 0xb2, 0x69, 0x43, 0x63, 0xbf, 0x41, 0x1c, 0x3e, 0x03, 0x99,
	0x90, 0x9e, 0x17, 0xca, 0xd5, 0xee, 0xf6, 0xfa, 0xf3, 0x7e, 0x55, 0x07, 0x6f, 0x03, 0x37, 0x8d,
	0xca, 0x76, 0x38, 0xfb, 0xb7, 0x03, 0xd1, 0x11, 0x81, 0x3d, 0x87, 0xe1, 0x9d, 0xb4, 0xe6, 0x60,
	0x65, 0x03, 0x0c, 0xd7, 0x02, 0x5b, 0x55, 0xdf, 0xeb, 0x94, 0xf1, 0x64, 0x66, 0x51, 0x0a, 0x01,
	0xfa, 0xa0, 0x8c, 0x47, 0xab, 0x2b, 0xad, 0x69, 0x7f, 0x15, 0x86, 0xa5, 0x35, 0xb4, 0x05, 0xcf,
	0xa0, 0xff, 0x57, 0xa1, 0x94, 0x23, 0xcb, 0x8a, 0xd2, 0x10, 0xb0, 0x0b, 0x18, 0x08, 0xc9, 0xfd,
	0x9d, 0x23, 0xb3, 0x8a, 0xd2, 0x3a, 0x62, 0x09, 0x0c, 0xb9, 0x73, 0x85, 0xf3, 0x8e, 0x8c, 0x2a,
	0x4a, 0x9b, 0x10, 0x75, 0x0a, 0x2f, 0xb5, 0x4b, 0x86, 0xf3, 0xee, 0xa2, 0x9b, 0x86, 0x60, 0xf6,
	0x27, 0xf4, 0x70, 0xf6, 0x59, 0x0c, 0x27, 0xfb, 0x7f, 0x7d, 0x52, 0x7c, 0xfe, 0xf3, 0x75, 0x06,
	0x5d, 0xdc, 0xc2, 0xf0, 0xff, 0xf0, 0x31, 0x38, 0x74, 0xbd, 0x4d, 0xe1, 0x5b, 0x35, 0x54, 0x61,
	0x8b, 0x6e, 0x07, 0xd4, 0xd1, 0x1f, 0xfe, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x81, 0x71, 0x67, 0x64,
	0x78, 0x07, 0x00, 0x00,
}
