// Code generated by modelgen. DO NOT EDIT.

package models

var _ Record = (*FollowedPlayer)(nil)

var FollowedPlayerModel Model = (*modelFollowedPlayer)(nil)

type modelFollowedPlayer struct{}

func (*modelFollowedPlayer) Name() string             { return "FollowedPlayer" }
func (*modelFollowedPlayer) Table() Table             { return FollowedPlayerTable }
func (*modelFollowedPlayer) NewRecord() Record        { return &FollowedPlayer{} }
func (*modelFollowedPlayer) NewSlicePtr() interface{} { return &[]*FollowedPlayer{} }

func (*modelFollowedPlayer) AsRecordSlice(v interface{}) ([]Record, error) {
	sptr, ok := v.(*[]*FollowedPlayer)

	if !ok {
		return nil, &ErrInvalidSliceType{Model: FollowedPlayerModel, Value: v}
	}

	if sptr == nil || *sptr == nil {
		return nil, nil
	}

	rs := make([]Record, len(*sptr))

	for i, r := range *sptr {
		rs[i] = r
	}

	return rs, nil
}

func (*modelFollowedPlayer) Associations() []Association {
	return nil
}

func (*modelFollowedPlayer) Association(name string) (Association, error) {
	return nil, &ErrNotAssociated{Model: FollowedPlayerModel, Assoc: name}
}

func (*FollowedPlayer) Model() Model {
	return FollowedPlayerModel
}

func (m *FollowedPlayer) AssignRecord(record Record) (bool, error) {
	if other, ok := record.(*FollowedPlayer); ok {
		return m.Assign(other), nil
	}

	return false, &ErrInvalidRecord{Model: m.Model(), Record: record}
}

func (m *FollowedPlayer) AssignPartialRecord(record Record) (bool, error) {
	if other, ok := record.(*FollowedPlayer); ok {
		return m.AssignPartial(other), nil
	}

	return false, &ErrInvalidRecord{Model: FollowedPlayerModel, Record: record}
}

func (m *FollowedPlayer) GetAssocPK(assoc string) (ID, error) {
	return m.ID, nil
}

func (m *FollowedPlayer) GetAssocFK(assoc string) (ID, error) {
	return 0, &ErrNotAssociated{Model: FollowedPlayerModel, Assoc: assoc}
}

func (m *FollowedPlayer) SetAssociated(assoc string, records ...Record) error {
	return &ErrNotAssociated{Model: FollowedPlayerModel, Assoc: assoc}
}
