// Code generated by modelgen. DO NOT EDIT.

package models

var _ Record = (*Hero)(nil)

var HeroModel Model = (*modelHero)(nil)

type modelHero struct{}

func (*modelHero) Name() string             { return "Hero" }
func (*modelHero) Table() Table             { return HeroTable }
func (*modelHero) NewRecord() Record        { return &Hero{} }
func (*modelHero) NewSlicePtr() interface{} { return &[]*Hero{} }

func (*modelHero) AsRecordSlice(v interface{}) ([]Record, error) {
	sptr, ok := v.(*[]*Hero)

	if !ok {
		return nil, &ErrInvalidSliceType{Model: HeroModel, Value: v}
	}

	if sptr == nil || *sptr == nil {
		return nil, nil
	}

	rs := make([]Record, len(*sptr))

	for i, r := range *sptr {
		rs[i] = r
	}

	return rs, nil
}

func (*modelHero) Associations() []Association {
	return nil
}

func (*modelHero) Association(name string) (Association, error) {
	return nil, &ErrNotAssociated{Model: HeroModel, Assoc: name}
}

func (*Hero) Model() Model {
	return HeroModel
}

func (m *Hero) AssignRecord(record Record) (bool, error) {
	if other, ok := record.(*Hero); ok {
		return m.Assign(other), nil
	}

	return false, &ErrInvalidRecord{Model: m.Model(), Record: record}
}

func (m *Hero) AssignPartialRecord(record Record) (bool, error) {
	if other, ok := record.(*Hero); ok {
		return m.AssignPartial(other), nil
	}

	return false, &ErrInvalidRecord{Model: HeroModel, Record: record}
}

func (m *Hero) GetAssocPK(assoc string) (ID, error) {
	return m.ID, nil
}

func (m *Hero) GetAssocFK(assoc string) (ID, error) {
	return 0, &ErrNotAssociated{Model: HeroModel, Assoc: assoc}
}

func (m *Hero) SetAssociated(assoc string, records ...Record) error {
	return &ErrNotAssociated{Model: HeroModel, Assoc: assoc}
}
