// Code generated by modelgen. DO NOT EDIT.

package models

import (
	nssql "github.com/13k/night-stalker/internal/sql"
)

// Assign assigns fields from "other" into the receiver.
// It returns true if any changes were made to the receiver.
func (m *LiveMatchPlayer) Assign(other *LiveMatchPlayer) (dirty bool) {
	if other == nil {
		return false
	}

	if m.ID != other.ID {
		m.ID = other.ID
		dirty = true
	}

	if m.AccountID != other.AccountID {
		m.AccountID = other.AccountID
		dirty = true
	}

	if m.LiveMatchID != other.LiveMatchID {
		m.LiveMatchID = other.LiveMatchID
		dirty = true
	}

	if m.MatchID != other.MatchID {
		m.MatchID = other.MatchID
		dirty = true
	}

	if m.HeroID != other.HeroID {
		m.HeroID = other.HeroID
		dirty = true
	}

	if !m.CreatedAt.Equal(other.CreatedAt) {
		m.CreatedAt = other.CreatedAt
		dirty = true
	}

	if !m.UpdatedAt.Equal(other.UpdatedAt) {
		m.UpdatedAt = other.UpdatedAt
		dirty = true
	}

	if !nssql.NullTimeEqual(m.DeletedAt, other.DeletedAt) {
		m.DeletedAt = other.DeletedAt
		dirty = true
	}

	return
}

// AssignPartial assigns fields with non-zero values from "other" into the receiver.
// It returns true if any changes were made to the receiver.
func (m *LiveMatchPlayer) AssignPartial(other *LiveMatchPlayer) (dirty bool) {
	if other == nil {
		return false
	}

	if other.ID != 0 && m.ID != other.ID {
		m.ID = other.ID
		dirty = true
	}

	if other.AccountID != 0 && m.AccountID != other.AccountID {
		m.AccountID = other.AccountID
		dirty = true
	}

	if other.LiveMatchID != 0 && m.LiveMatchID != other.LiveMatchID {
		m.LiveMatchID = other.LiveMatchID
		dirty = true
	}

	if other.MatchID != 0 && m.MatchID != other.MatchID {
		m.MatchID = other.MatchID
		dirty = true
	}

	if other.HeroID != 0 && m.HeroID != other.HeroID {
		m.HeroID = other.HeroID
		dirty = true
	}

	if !other.CreatedAt.IsZero() && !m.CreatedAt.Equal(other.CreatedAt) {
		m.CreatedAt = other.CreatedAt
		dirty = true
	}

	if !other.UpdatedAt.IsZero() && !m.UpdatedAt.Equal(other.UpdatedAt) {
		m.UpdatedAt = other.UpdatedAt
		dirty = true
	}

	if !nssql.NullTimeIsZero(other.DeletedAt) && !nssql.NullTimeEqual(m.DeletedAt, other.DeletedAt) {
		m.DeletedAt = other.DeletedAt
		dirty = true
	}

	return
}
