// Code generated by modelgen. DO NOT EDIT.

package models

import (
	nssql "github.com/13k/night-stalker/internal/sql"
)

// Assign assigns fields from "other" into the receiver.
// It returns true if any changes were made to the receiver.
func (m *LiveMatchStatsTeam) Assign(other *LiveMatchStatsTeam) (dirty bool) {
	if other == nil {
		return false
	}

	if m.ID != other.ID {
		m.ID = other.ID
		dirty = true
	}

	if m.GameTeam != other.GameTeam {
		m.GameTeam = other.GameTeam
		dirty = true
	}

	if m.Name != other.Name {
		m.Name = other.Name
		dirty = true
	}

	if m.Tag != other.Tag {
		m.Tag = other.Tag
		dirty = true
	}

	if m.LogoID != other.LogoID {
		m.LogoID = other.LogoID
		dirty = true
	}

	if m.LogoURL != other.LogoURL {
		m.LogoURL = other.LogoURL
		dirty = true
	}

	if m.Score != other.Score {
		m.Score = other.Score
		dirty = true
	}

	if m.NetWorth != other.NetWorth {
		m.NetWorth = other.NetWorth
		dirty = true
	}

	if m.LiveMatchStatsID != other.LiveMatchStatsID {
		m.LiveMatchStatsID = other.LiveMatchStatsID
		dirty = true
	}

	if m.TeamID != other.TeamID {
		m.TeamID = other.TeamID
		dirty = true
	}

	if !m.CreatedAt.Equal(other.CreatedAt) {
		m.CreatedAt = other.CreatedAt
		dirty = true
	}

	if !m.UpdatedAt.Equal(other.UpdatedAt) {
		m.UpdatedAt = other.UpdatedAt
		dirty = true
	}

	if !nssql.NullTimeEqual(m.DeletedAt, other.DeletedAt) {
		m.DeletedAt = other.DeletedAt
		dirty = true
	}

	return
}

// AssignPartial assigns fields with non-zero values from "other" into the receiver.
// It returns true if any changes were made to the receiver.
func (m *LiveMatchStatsTeam) AssignPartial(other *LiveMatchStatsTeam) (dirty bool) {
	if other == nil {
		return false
	}

	if other.ID != 0 && m.ID != other.ID {
		m.ID = other.ID
		dirty = true
	}

	if other.GameTeam != 0 && m.GameTeam != other.GameTeam {
		m.GameTeam = other.GameTeam
		dirty = true
	}

	if other.Name != "" && m.Name != other.Name {
		m.Name = other.Name
		dirty = true
	}

	if other.Tag != "" && m.Tag != other.Tag {
		m.Tag = other.Tag
		dirty = true
	}

	if other.LogoID != 0 && m.LogoID != other.LogoID {
		m.LogoID = other.LogoID
		dirty = true
	}

	if other.LogoURL != "" && m.LogoURL != other.LogoURL {
		m.LogoURL = other.LogoURL
		dirty = true
	}

	if other.Score != 0 && m.Score != other.Score {
		m.Score = other.Score
		dirty = true
	}

	if other.NetWorth != 0 && m.NetWorth != other.NetWorth {
		m.NetWorth = other.NetWorth
		dirty = true
	}

	if other.LiveMatchStatsID != 0 && m.LiveMatchStatsID != other.LiveMatchStatsID {
		m.LiveMatchStatsID = other.LiveMatchStatsID
		dirty = true
	}

	if other.TeamID != 0 && m.TeamID != other.TeamID {
		m.TeamID = other.TeamID
		dirty = true
	}

	if !other.CreatedAt.IsZero() && !m.CreatedAt.Equal(other.CreatedAt) {
		m.CreatedAt = other.CreatedAt
		dirty = true
	}

	if !other.UpdatedAt.IsZero() && !m.UpdatedAt.Equal(other.UpdatedAt) {
		m.UpdatedAt = other.UpdatedAt
		dirty = true
	}

	if !nssql.NullTimeIsZero(other.DeletedAt) && !nssql.NullTimeEqual(m.DeletedAt, other.DeletedAt) {
		m.DeletedAt = other.DeletedAt
		dirty = true
	}

	return
}
