// Code generated by modelgen. DO NOT EDIT.

package models

var _ Record = (*LiveMatchStatsPlayer)(nil)

var LiveMatchStatsPlayerModel Model = (*modelLiveMatchStatsPlayer)(nil)

// uses an anonymous struct to have compile-time checks when using associations
var assocLiveMatchStatsPlayer = struct {
	LiveMatchStats Association
	Match          Association
	Hero           Association
}{
	LiveMatchStats: NewAssociation(
		BelongsTo,
		&ModelAssociation{Model: LiveMatchStatsPlayerModel, Name: "LiveMatchStats", PK: "id", FK: "live_match_stats_id"},
		&ModelAssociation{Model: LiveMatchStatsModel, Name: "LiveMatchStatsPlayer", PK: "id", FK: ""},
	),
	Match: NewAssociation(
		BelongsTo,
		&ModelAssociation{Model: LiveMatchStatsPlayerModel, Name: "Match", PK: "id", FK: "match_id"},
		&ModelAssociation{Model: MatchModel, Name: "LiveMatchStatsPlayer", PK: "id", FK: ""},
	),
	Hero: NewAssociation(
		BelongsTo,
		&ModelAssociation{Model: LiveMatchStatsPlayerModel, Name: "Hero", PK: "id", FK: "hero_id"},
		&ModelAssociation{Model: HeroModel, Name: "LiveMatchStatsPlayer", PK: "id", FK: ""},
	),
}

type modelLiveMatchStatsPlayer struct{}

func (*modelLiveMatchStatsPlayer) Name() string             { return "LiveMatchStatsPlayer" }
func (*modelLiveMatchStatsPlayer) Table() Table             { return LiveMatchStatsPlayerTable }
func (*modelLiveMatchStatsPlayer) NewRecord() Record        { return &LiveMatchStatsPlayer{} }
func (*modelLiveMatchStatsPlayer) NewSlicePtr() interface{} { return &[]*LiveMatchStatsPlayer{} }

func (*modelLiveMatchStatsPlayer) AsRecordSlice(v interface{}) ([]Record, error) {
	sptr, ok := v.(*[]*LiveMatchStatsPlayer)

	if !ok {
		return nil, &ErrInvalidSliceType{Model: LiveMatchStatsPlayerModel, Value: v}
	}

	if sptr == nil || *sptr == nil {
		return nil, nil
	}

	rs := make([]Record, len(*sptr))

	for i, r := range *sptr {
		rs[i] = r
	}

	return rs, nil
}

func (*modelLiveMatchStatsPlayer) Associations() []Association {
	return []Association{
		assocLiveMatchStatsPlayer.LiveMatchStats,
		assocLiveMatchStatsPlayer.Match,
		assocLiveMatchStatsPlayer.Hero,
	}
}

func (*modelLiveMatchStatsPlayer) Association(name string) (Association, error) {
	switch name {
	case "LiveMatchStats":
		return assocLiveMatchStatsPlayer.LiveMatchStats, nil
	case "Match":
		return assocLiveMatchStatsPlayer.Match, nil
	case "Hero":
		return assocLiveMatchStatsPlayer.Hero, nil
	}

	return nil, &ErrNotAssociated{Model: LiveMatchStatsPlayerModel, Assoc: name}
}

func (*LiveMatchStatsPlayer) Model() Model {
	return LiveMatchStatsPlayerModel
}

func (m *LiveMatchStatsPlayer) AssignRecord(record Record) (bool, error) {
	if other, ok := record.(*LiveMatchStatsPlayer); ok {
		return m.Assign(other), nil
	}

	return false, &ErrInvalidRecord{Model: m.Model(), Record: record}
}

func (m *LiveMatchStatsPlayer) AssignPartialRecord(record Record) (bool, error) {
	if other, ok := record.(*LiveMatchStatsPlayer); ok {
		return m.AssignPartial(other), nil
	}

	return false, &ErrInvalidRecord{Model: LiveMatchStatsPlayerModel, Record: record}
}

func (m *LiveMatchStatsPlayer) GetAssocPK(assoc string) (ID, error) {
	return m.ID, nil
}

func (m *LiveMatchStatsPlayer) GetAssocFK(assoc string) (ID, error) {
	switch assoc {
	case "LiveMatchStats":
		return m.LiveMatchStatsID, nil
	case "Match":
		return m.MatchID, nil
	case "Hero":
		return m.HeroID, nil
	}

	return 0, &ErrNotAssociated{Model: LiveMatchStatsPlayerModel, Assoc: assoc}
}

func (m *LiveMatchStatsPlayer) SetAssociated(assoc string, records ...Record) error {
	if len(records) == 0 {
		return nil
	}

	switch assoc {
	case "LiveMatchStats":
		r := records[0]

		if mr, ok := r.(*LiveMatchStats); ok {
			m.LiveMatchStats = mr
			return nil
		}

		return &ErrInvalidAssociationRecord{Assoc: assocLiveMatchStatsPlayer.LiveMatchStats, Record: r}
	case "Match":
		r := records[0]

		if mr, ok := r.(*Match); ok {
			m.Match = mr
			return nil
		}

		return &ErrInvalidAssociationRecord{Assoc: assocLiveMatchStatsPlayer.Match, Record: r}
	case "Hero":
		r := records[0]

		if mr, ok := r.(*Hero); ok {
			m.Hero = mr
			return nil
		}

		return &ErrInvalidAssociationRecord{Assoc: assocLiveMatchStatsPlayer.Hero, Record: r}
	}

	return &ErrNotAssociated{Model: LiveMatchStatsPlayerModel, Assoc: assoc}
}
