// Code generated by modelgen. DO NOT EDIT.

package models

var _ Record = (*PlayerProfileCard)(nil)

var PlayerProfileCardModel Model = (*modelPlayerProfileCard)(nil)

type modelPlayerProfileCard struct{}

func (*modelPlayerProfileCard) Name() string             { return "PlayerProfileCard" }
func (*modelPlayerProfileCard) Table() Table             { return PlayerProfileCardTable }
func (*modelPlayerProfileCard) NewRecord() Record        { return &PlayerProfileCard{} }
func (*modelPlayerProfileCard) NewSlicePtr() interface{} { return &[]*PlayerProfileCard{} }

func (*modelPlayerProfileCard) AsRecordSlice(v interface{}) ([]Record, error) {
	sptr, ok := v.(*[]*PlayerProfileCard)

	if !ok {
		return nil, &ErrInvalidSliceType{Model: PlayerProfileCardModel, Value: v}
	}

	if sptr == nil || *sptr == nil {
		return nil, nil
	}

	rs := make([]Record, len(*sptr))

	for i, r := range *sptr {
		rs[i] = r
	}

	return rs, nil
}

func (*modelPlayerProfileCard) Associations() []Association {
	return nil
}

func (*modelPlayerProfileCard) Association(name string) (Association, error) {
	return nil, &ErrNotAssociated{Model: PlayerProfileCardModel, Assoc: name}
}

func (*PlayerProfileCard) Model() Model {
	return PlayerProfileCardModel
}

func (m *PlayerProfileCard) AssignRecord(record Record) (bool, error) {
	if other, ok := record.(*PlayerProfileCard); ok {
		return m.Assign(other), nil
	}

	return false, &ErrInvalidRecord{Model: m.Model(), Record: record}
}

func (m *PlayerProfileCard) AssignPartialRecord(record Record) (bool, error) {
	if other, ok := record.(*PlayerProfileCard); ok {
		return m.AssignPartial(other), nil
	}

	return false, &ErrInvalidRecord{Model: PlayerProfileCardModel, Record: record}
}

func (m *PlayerProfileCard) GetAssocPK(assoc string) (ID, error) {
	return m.ID, nil
}

func (m *PlayerProfileCard) GetAssocFK(assoc string) (ID, error) {
	return 0, &ErrNotAssociated{Model: PlayerProfileCardModel, Assoc: assoc}
}

func (m *PlayerProfileCard) SetAssociated(assoc string, records ...Record) error {
	return &ErrNotAssociated{Model: PlayerProfileCardModel, Assoc: assoc}
}
